functions: [checkEndpointStatusCodes, checkNumericLimits]
extends: spectral:oas
rules:
  my-rule:
    message: "{{error}}"
    severity: error
    given: $.
    then:
      function: checkEndpointStatusCodes
  numeric-limits-rule:
    message: "{{error}}"
    severity: error
    given: $.
    then:
      function: checkNumericLimits
