components:
  schemas:
    AuthToken:
      additionalProperties: false
      properties:
        client_id:
          type: string
        created_at:
          format: date-time
          type: string
        deleted_at:
          format: date-time
          type: string
        description:
          type: string
        id:
          format: int64
          type: integer
        is_active:
          type: boolean
        last_editor:
          type: string
        name:
          type: string
        token:
          type: string
        updated_at:
          format: date-time
          type: string
      required:
      - client_id
      - created_at
      - id
      - is_active
      - last_editor
      - name
      - token
      - updated_at
      type: object
    CreateCredentialRequest:
      additionalProperties: false
      properties:
        description:
          type: string
        name:
          type: string
        status:
          type: boolean
      required:
      - name
      - description
      - status
      type: object
    Response:
      additionalProperties: false
      properties:
        description:
          type: string
        id:
          format: int64
          type: integer
        last_editor:
          type: string
        last_modified:
          format: date-time
          type: string
        name:
          type: string
        status:
          type: boolean
        token:
          type: string
      required:
      - id
      - name
      - token
      - status
      - description
      - last_editor
      - last_modified
      type: object
    ResponseWithTotal:
      additionalProperties: false
      properties:
        credentials:
          items:
            $ref: '#/components/schemas/Response'
          type: array
        total:
          format: int64
          type: integer
      required:
      - credentials
      - total
      type: object
    UpdateCredentialRequest:
      additionalProperties: false
      properties:
        description:
          type: string
        name:
          type: string
        status:
          type: boolean
      required:
      - name
      - description
      - status
      type: object
  securitySchemes:
    tokenAuth:
      type: apiKey
      name: Authorization
      in: header
      description: |
        You must inform a token to auth.
        Usage format: `Token <TOKEN>`
info:
  description: Azion Orchestration
  title: Credentials API
  version: 2.0.0
openapi: 3.0.0
paths:
  /credentials:
    get:
      operationId: findAll
      parameters:
      - in: query
        name: filter
        schema:
          type: string
      - in: query
        name: page
        schema:
          format: int64
          type: integer
      - in: query
        name: page_size
        schema:
          format: int64
          type: integer
      - in: query
        name: sort
        schema:
          type: string
      - in: query
        name: order_by
        schema:
          type: string
      responses:
        "200":
          content:
            'application/json; version=3':
              schema:
                $ref: '#/components/schemas/ResponseWithTotal'
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Return all credentials
    post:
      operationId: createCredential
      requestBody:
        content:
          'application/json; version=3':
            schema:
              $ref: '#/components/schemas/CreateCredentialRequest'
        required: true
      responses:
        "201":
          content:
            'application/json; version=3':
              schema:
                $ref: '#/components/schemas/AuthToken'
          description: Created
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Create credential
  /credentials/{credentialId}:
    delete:
      operationId: deleteCredential
      parameters:
      - in: path
        name: credentialId
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete the Credential
    get:
      operationId: loadCredential
      parameters:
      - in: path
        name: credentialId
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            'application/json; version=3':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Load the Credential
    patch:
      operationId: updateCredential
      parameters:
      - in: path
        name: credentialId
        required: true
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          'application/json; version=3':
            schema:
              $ref: '#/components/schemas/UpdateCredentialRequest'
        required: true
      responses:
        "200":
          content:
            'application/json; version=3':
              schema:
                $ref: '#/components/schemas/Response'
          description: OK
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Update the Credential
security:
- tokenAuth: []
servers:
- description: Local Dev
  url: http://localhost:3007
- description: Staging
  url: https://stage-api.azion.net
- description: Production
  url: https://api.azionapi.net
