openapi: 3.0.0
info:
  title: Domain
servers:
  - url: https://api.azionapi.net
security:
- tokenAuth: []
components:
  schemas:
    CreateDomainRequest:
      additionalProperties: false
      properties:
        cnames:
          type: array
          items:
            type: string
        cname_access_only:
          type: boolean
        name:
          type: string
        is_active:
          type: boolean
        edge_application_id:
          format: int64
          type: integer
        digital_certificate_id:
          format: int64
          type: integer
          nullable: true
      required:
      - name
      - edge_application_id
      - cname_access_only
      - cnames
      - is_active
      - digital_certificate_id
      type: object
    UpdateDomainRequest:
      additionalProperties: false
      properties:
        cnames:
          type: array
          items:
            type: string
        cname_access_only:
          type: boolean
        name:
          type: string
        is_active:
          type: boolean
        edge_application_id:
          format: int64
          type: integer
        digital_certificate_id:
          format: int64
          type: integer
          nullable: true
      type: object
    PutDomainRequest:
      additionalProperties: false
      properties:
        cnames:
          type: array
          items:
            type: string
        cname_access_only:
          type: boolean
        name:
          type: string
        is_active:
          type: boolean
        edge_application_id:
          format: int64
          type: integer
        digital_certificate_id:
          format: int64
          type: integer
          nullable: true
      required:
      - name
      - edge_application_id
      - cname_access_only
      - cnames
      - is_active
      - digital_certificate_id
      type: object
    DomainLinks:
      additionalProperties: false
      properties:
        previous:
          type: string
        next:
          type: string
      required:
      - previous
      - next
      type: object
    DomainResponseWithResults:
      additionalProperties: false
      properties:
        count:
          format: int64
          type: integer
        total_pages:
          format: int64
          type: integer
        schema_version:
          format: int64
          type: integer
        links:
          $ref: '#/components/schemas/DomainLinks'
          type: object
        results:
          items:
            $ref: '#/components/schemas/DomainResults'
          type: array
      required:
      - count
      - total_pages
      - schema_version
      - links
      - results
      type: object
    DomainResponseWithResult:
      additionalProperties: false
      properties:
        schema_version:
          format: int64
          type: integer
        results:
          $ref: '#/components/schemas/DomainResults'
          type: object
      required:
      - schema_version
      - results
      type: object
    DomainResults:
      additionalProperties: false
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        cnames:
          type: array
          items:
            type: string
        cname_access_only:
          type: boolean
        is_active:
          type: boolean
        edge_application_id:
          format: int64
          type: integer
        digital_certificate_id:
          format: int64
          type: integer
          nullable: true
        domain_name:
          type: string
        environment:
          type: string
      required:
      - id
      - name
      - type
      - content_type
      - last_editor
      - updated_at
      type: object
  securitySchemes:
    tokenAuth:
      type: apiKey
      name: Authorization
      in: header
      description: |
        You must inform a token to auth.
        Usage format: `Token <TOKEN>`
tags:
  - name: Domains
    description: >-
      Through My Domains API you can retrieve, create, remove or update Domains
      used by Edge Applications
paths:
  /domains:
    get:
      tags:
        - Domains
      summary: /domains
      description: It returns the list of domains of an account.
      operationId: getDomains
      parameters:
        - explode: true
          in: query
          name: page
          required: false
          schema:
            format: int64
            type: integer
          style: form
        - explode: true
          in: query
          name: page_size
          required: false
          schema:
            format: int64
            type: integer
          style: form
        - explode: true
          in: query
          name: sort
          required: false
          schema:
            type: string
          style: form
        - explode: true
          in: query
          name: order_by
          required: false
          schema:
            type: string
          style: form
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json; version=3
      responses:
        '200':
          description: Successful response
          content:
            application/json; version=3:
              schema:
                $ref: "#/components/schemas/DomainResponseWithResults"
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
            
    post:
      tags:
        - Domains
      summary: /domains
      description: It enables you to include a new domain into an account.
      requestBody:
        content:
          application/json; version=3:
            schema:
              $ref: '#/components/schemas/CreateDomainRequest'
              example:
                name: My Domain
                cnames: []
                cname_access_only: false
                digital_certificate_id: null
                edge_application_id: 1580476573
                is_active: true
      operationId: createDomain
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json; version=3
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json; version=3:
              schema:
                $ref: "#/components/schemas/DomainResponseWithResult"
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
  /domains/{id}:
    get:
      tags:
        - Domains
      summary: /domains/:id
      description: It returns details of a domain.
      operationId: getDomain
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json; version=3
        - name: id
          in: path
          schema:
            type: string
          required: true
          description: "The id of the domain to be consulted.\t"
      responses:
        '200':
          description: Successful response
          content:
            application/json; version=3:
              schema:
                $ref: "#/components/schemas/DomainResponseWithResult"
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
    delete:
      tags:
        - Domains
      summary: /domains/:id
      description: It enables you to delete a domain.
      operationId: delDomain
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json; version=3
        - name: id
          in: path
          schema:
            type: string
          required: true
          description: "The id of the domain to be deleted.\t"
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
    put:
      tags:
        - Domains
      summary: /domains:/:id
      description: >-
        It overwrites all fields of a domain, while preserving the id. Optional
        fields not filled in will be replaced by the default values.


        To update only some fields in a domain, consider using the PATCH method
        instead of PUT.
      requestBody:
        content:
          application/json; version=3:
            schema:
              $ref: '#/components/schemas/PutDomainRequest'
              example:
                name: My Domain
                cnames: []
                cname_access_only: false
                digital_certificate_id: null
                edge_application_id: 1580476573
                is_active: true
      operationId: putDomain
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json; version=3
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json; version=3:
              schema:
                $ref: "#/components/schemas/DomainResponseWithResult"
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
    patch:
      tags:
        - Domains
      summary: /domains/:id
      description: >-
        It updates one or more fields in a Domain, preserving the value of the
        fields not informed.
      requestBody:
        content:
          application/json; version=3:
            schema:
              $ref: '#/components/schemas/UpdateDomainRequest'
              example:
                name: Validation Fafinha
                cnames: []
                cname_access_only: false
                digital_certificate_id: null
                edge_application_id: 1580476573
                is_active: true
      operationId: updateDomain
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json; version=3
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json; version=3:
              schema:
                $ref: "#/components/schemas/DomainResponseWithResult"
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
