components:
  schemas:
    AuthorizeEdgeNodesRequest:
      additionalProperties: false
      properties:
        edge_node_ids:
          items:
            format: int64
            type: integer
          type: array
      required:
      - edge_node_ids
      type: object
    AuthorizeEdgeNodesResponse:
      additionalProperties: false
      properties:
        authorized:
          items:
            format: int64
            type: integer
          type: array
        errors:
          items:
            $ref: '#/components/schemas/UnauthorizedEdgeNodeInfo'
          type: array
      required:
      - authorized
      - errors
      type: object
    EdgeNodeDetailResponse:
      additionalProperties: false
      properties:
        groups:
          items:
            $ref: '#/components/schemas/NodeGroup'
          type: array
        has_services:
          type: boolean
        hash_id:
          type: string
        id:
          format: int64
          type: integer
        modules:
          $ref: '#/components/schemas/EdgeNodeModules'
        name:
          type: string
      required:
      - id
      - hash_id
      - name
      - groups
      - modules
      - has_services
      type: object
    EdgeNodeModules:
      additionalProperties: false
      properties:
        add_services:
          type: boolean
      required:
      - add_services
      type: object
    EdgeNodeResponse:
      additionalProperties: false
      properties:
        groups:
          items:
            $ref: '#/components/schemas/NodeGroup'
          type: array
        hash_id:
          type: string
        id:
          format: int64
          type: integer
        name:
          type: string
        status:
          type: string
      required:
      - id
      type: object
    EdgeNodeResponseWithTotal:
      additionalProperties: false
      properties:
        nodes:
          items:
            $ref: '#/components/schemas/EdgeNodeResponse'
          type: array
        total:
          format: int64
          type: integer
      required:
      - nodes
      - total
      type: object
    NodeGroup:
      additionalProperties: false
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
      required:
      - id
      - name
      type: object
    NodeGroupResponse:
      additionalProperties: false
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
      required:
      - id
      - name
      type: object
    ServiceBindDetailResponse:
      additionalProperties: false
      properties:
        id:
          format: int64
          type: integer
        service_id:
          format: int64
          type: integer
        service_name:
          type: string
        variables:
          items:
            $ref: '#/components/schemas/Variable'
          type: array
      required:
      - id
      - service_name
      - service_id
      - variables
      type: object
    ServiceBindRequest:
      additionalProperties: false
      properties:
        service_id:
          format: int64
          type: integer
        variables:
          items:
            $ref: '#/components/schemas/Variable'
          type: array
      required:
      - service_id
      - variables
      type: object
    ServiceResponse:
      additionalProperties: false
      properties:
        bind_id:
          format: int64
          type: integer
        is_bound:
          format: int64
          type: integer
        last_editor:
          type: string
        name:
          type: string
        service_id:
          format: int64
          type: integer
        updated_at:
          format: date-time
          type: string
      required:
      - service_id
      - name
      - is_bound
      - bind_id
      - updated_at
      - last_editor
      type: object
    ServiceResponseWithTotal:
      additionalProperties: false
      properties:
        services:
          items:
            $ref: '#/components/schemas/ServiceResponse'
          type: array
        total:
          format: int64
          type: integer
      required:
      - services
      - total
      type: object
    UnauthorizedEdgeNodeInfo:
      additionalProperties: false
      properties:
        id:
          format: int64
          type: integer
        reason:
          type: string
      required:
      - id
      - reason
      type: object
    UpdateEdgeNodeResponse:
      additionalProperties: false
      properties:
        groups:
          items:
            $ref: '#/components/schemas/NodeGroup'
          type: array
        id:
          format: int64
          type: integer
        name:
          type: string
        status:
          type: string
      required:
      - id
      - name
      - groups
      - status
      type: object
    UpdateServiceBindRequest:
      additionalProperties: false
      properties:
        variables:
          items:
            $ref: '#/components/schemas/Variable'
          type: array
      required:
      - variables
      type: object
    Variable:
      additionalProperties: false
      properties:
        name:
          type: string
        value:
          type: string
      required:
      - name
      - value
      type: object
  securitySchemes:
    bearerAuth:
      type: apiKey
      name: Authorization
      in: header
info:
  description: Azion Orchestration
  title: Edgenode API
  version: 2.0.0
openapi: 3.0.0
paths:
  /edge_nodes/:
    get:
      operationId: getEdgeNodes
      parameters:
      - in: query
        name: filter
        schema:
          type: string
      - in: query
        name: order_by
        schema:
          type: string
      - in: query
        name: sort
        schema:
          type: string
      - in: query
        name: only_ids
        schema:
          type: boolean
      - in: query
        name: page_size
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            'application/json; version=3':
              schema:
                $ref: '#/components/schemas/EdgeNodeResponseWithTotal'
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Return edge-nodes
  /edge_nodes/{edgenodeId}:
    delete:
      operationId: delEdgeNode
      parameters:
      - in: path
        name: edgenodeId
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete edge-node by ID
    get:
      operationId: getEdgeNode
      parameters:
      - in: path
        name: edgenodeId
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            'application/json; version=3':
              schema:
                $ref: '#/components/schemas/EdgeNodeDetailResponse'
          description: OK
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Return edge-node by ID
    patch:
      operationId: updateEdgeNode
      parameters:
      - in: path
        name: edgenodeId
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            'application/json; version=3':
              schema:
                $ref: '#/components/schemas/UpdateEdgeNodeResponse'
          description: OK
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Update edge-node
  /edge_nodes/{edgenodeId}/services:
    get:
      operationId: getEdgeNodeSvcs
      parameters:
      - in: path
        name: edgenodeId
        required: true
        schema:
          format: int64
          type: integer
      - in: query
        name: is_bound
        schema:
          type: boolean
      - in: query
        name: filter
        schema:
          type: string
      - in: query
        name: order_by
        schema:
          type: string
      - in: query
        name: sort
        schema:
          type: string
      - in: query
        name: page
        schema:
          format: int64
          type: integer
      - in: query
        name: page_size
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            'application/json; version=3':
              schema:
                $ref: '#/components/schemas/ServiceResponseWithTotal'
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Return edge-node Services association
    post:
      operationId: createEdgeNodeSvcs
      parameters:
      - in: path
        name: edgenodeId
        required: true
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          'application/json; version=3':
            schema:
              $ref: '#/components/schemas/ServiceBindRequest'
        required: true
      responses:
        "201":
          content:
            'application/json; version=3':
              schema:
                $ref: '#/components/schemas/ServiceBindDetailResponse'
          description: Created
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Create an edge-node Service association
  /edge_nodes/{edgenodeId}/services/{bindId}:
    delete:
      operationId: delEdgeNodeSvc
      parameters:
      - in: path
        name: edgenodeId
        required: true
        schema:
          format: int64
          type: integer
      - in: path
        name: bindId
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete an edge-node Service association
    get:
      operationId: getEdgeNodeSvcDetail
      parameters:
      - in: path
        name: edgenodeId
        required: true
        schema:
          format: int64
          type: integer
      - in: path
        name: bindId
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            'application/json; version=3':
              schema:
                $ref: '#/components/schemas/ServiceBindDetailResponse'
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Return edge-node Service association by ID
    patch:
      operationId: updateEdgeNodeSvcDetail
      parameters:
      - in: path
        name: edgenodeId
        required: true
        schema:
          format: int64
          type: integer
      - in: path
        name: bindId
        required: true
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          'application/json; version=3':
            schema:
              $ref: '#/components/schemas/UpdateServiceBindRequest'
        required: true
      responses:
        "200":
          content:
            'application/json; version=3':
              schema:
                $ref: '#/components/schemas/ServiceBindDetailResponse'
          description: OK
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
      summary: Update edge-node Service association by ID
  /edge_nodes/authorize:
    patch:
      operationId: authorizeEdgeNode
      requestBody:
        content:
          'application/json; version=3':
            schema:
              $ref: '#/components/schemas/AuthorizeEdgeNodesRequest'
        required: true
      responses:
        "200":
          content:
            'application/json; version=3':
              schema:
                $ref: '#/components/schemas/AuthorizeEdgeNodesResponse'
          description: OK
        "400":
          description: Bad Request
        "422":
          description: Unprocessable Entity
      summary: Authorize edge-node
  /edge_nodes/groups:
    get:
      operationId: getEdgeNodeGroups
      responses:
        "200":
          content:
            'application/json; version=3':
              schema:
                items:
                  $ref: '#/components/schemas/NodeGroupResponse'
                type: array
          description: OK
        "500":
          description: Internal Server Error
      summary: Return edge-node groups
security:
- bearerAuth: []
servers:
- description: Local Dev
  url: http://localhost:3001
- description: Staging
  url: https://stage-api.azion.net
- description: Production
  url: https://api.azionapi.net
