openapi: 3.0.0
info:
  title: Azion API
  version: "3.0"
servers:
- url: https://api.azionapi.net/
paths:
  /edge_firewall/:edge_firewall_id:/functions_instances:
    get:
      summary: List all user Edge Functions Instances
      parameters:
      - name: page
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: page_size
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: sort
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: order_by
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: A list of Edge Functions Instances
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListEdgeFunctionsInstancesResponse'
    post:
      summary: Create an Edge Functions Instance
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEdgeFunctionsInstancesRequest'
        required: true
      responses:
        "201":
          description: Edge Functions Instance created
        "400":
          $ref: '#/components/schemas/BadRequestResponse'
        "500":
          $ref: '#/components/schemas/ErrorModel'
  /edge_firewall/:edge_firewall_id:/functions_instances/{uuid}:
    get:
      summary: Retrieve an Edge Functions Instance set by uuid
      parameters:
      - name: uuid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: An Edge Functions Instance object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EdgeFunctionsInstanceResponse'
    put:
      summary: Overwrite some Edge Functions Instance attributes
      parameters:
      - name: uuid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEdgeFunctionsInstanceRequest'
        required: true
      responses:
        "200":
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListEdgeFunctionsInstancesResponse'
        "400":
          $ref: '#/components/schemas/BadRequestResponse'
        "500":
          $ref: '#/components/schemas/ErrorModel'
    delete:
      summary: Delete an Edge Functions Instance by uuid
      parameters:
      - name: uuid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: Successfully deleted
    patch:
      summary: Update some Edge Functions Instance attributes
      parameters:
      - name: uuid
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEdgeFunctionsInstanceRequest'
        required: true
      responses:
        "200":
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListEdgeFunctionsInstancesResponse'
        "400":
          $ref: '#/components/schemas/BadRequestResponse'
        "500":
          $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    ErrorModel:
      type: object
      properties:
        code:
          type: string
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
    Links:
      type: object
      properties:
        previous:
          type: string
        next:
          type: string
      example:
        next: next
        previous: previous
    EdgeFunctionsInstance:
      type: object
      properties:
        id:
          type: integer
          example: 1614
        name:
          type: string
          example: asdasdsad
        json_args:
          type: object
          example: {}
        edge_function:
          type: integer
          example: 3254
      example:
        edge_function: 3254
        name: asdasdsad
        json_args: {}
        id: 1614
    ListEdgeFunctionsInstancesResponse:
      type: object
      properties:
        count:
          type: integer
          format: int64
        total_pages:
          type: integer
          format: int64
        schema_version:
          type: integer
          format: int64
        links:
          $ref: '#/components/schemas/Links'
        results:
          type: array
          items:
            $ref: '#/components/schemas/EdgeFunctionsInstance'
      example:
        schema_version: 1
        count: 0
        links:
          next: next
          previous: previous
        total_pages: 6
        results:
        - edge_function: 3254
          name: asdasdsad
          json_args: {}
          id: 1614
        - edge_function: 3254
          name: asdasdsad
          json_args: {}
          id: 1614
    CreateEdgeFunctionsInstancesRequest:
      type: object
      properties:
        name:
          type: string
          example: Edge Functions Instance
        edge_function:
          type: integer
          example: 13
        json_args:
          type: object
          example: {}
    BadRequestResponse:
      type: object
      properties:
        name:
          type: array
          items:
            type: string
        edge_function:
          type: array
          items:
            type: string
        json_args:
          type: array
          items:
            type: string
    EdgeFunctionsInstanceResponse:
      type: object
      properties:
        results:
          $ref: '#/components/schemas/EdgeFunctionsInstance'
        schema_version:
          type: number
      example:
        schema_version: 0.80082819046101150206595775671303272247314453125
        results:
          edge_function: 3254
          name: asdasdsad
          json_args: {}
          id: 1614
    UpdateEdgeFunctionsInstanceRequest:
      $ref: '#/components/schemas/CreateEdgeFunctionsInstancesRequest'
  securitySchemes:
    JWT:
      type: apiKey
      description: |
        You must inform a token to auth.
        Usage format: `Token <TOKEN>`
      name: Authorization
      in: header
