openapi: 3.0.0
info:
  title: Network Lists API
  version: 1.0.0
  license:
    name: MIT
    url: https://github.com/aziontech/azionapi-openapi/blob/main/LICENSE.md
servers:
  - description: Production
    url: https://api.azionapi.net
security:
  - tokenAuth: []
paths:
  /network_lists:
    post:
      summary: Create a Network Lists
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNetworkListsRequest'
      responses:
        '201':
          description: A Network Lists object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkListsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
            text/html:
              schema:
                type: string
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
    get:
      summary: List all user Network Lists
      parameters:
        - name: page
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: integer
        - name: page_size
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: integer
        - name: sort
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: order_by
          in: query
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: A list of Network Lists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListNetworkListsResponse'
        '400': 
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
            text/html:
              schema:
                type: string
        '404':
          description: Not Found
  /network_lists/{uuid}:
    get:
      summary: Retrieve a Network Lists set by uuid
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A Network Lists object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkListUuidResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
            text/html:
              schema:
                type: string
        '404':
          description: Not Found
    delete:
      summary: Delete a Network Lists set by uuid
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json; version=3
        - name: uuid
          in: path
          schema:
            type: string
          required: true
          description: "The id of the networkList to be deleted.\t"
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
        "500":
          description: Internal Server Error
    put:
      summary: Overwrite some Network Lists attributes
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNetworkListsRequest'
      responses:
        '200':
          description: Successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NetworkListsResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
            text/html:
              schema:
                type: string
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    ErrorModel:
      properties:
        code:
          type: string
      type: object
    Links:
      properties:
        previous:
          type: string
          nullable: true
        next:
          type: string
          nullable: true
      type: object
    NetworkLists:
      properties:
        id:
          format: int64
          type: integer
          example: 1614
        last_editor:
          type: string
          example: Azion
        last_modified:
          type: string
          example: 2023-08-10T05:00:07.893747Z
        list_type:
          type: string
          example: ip_cidr
        name:
          type: string
          example: Network List created using the API
        country_list:
          type: array
          items:
            type: string
        ip_list:
          type: array
          items:
            type: string
          example:
            - 192.168.0.1
      type: object
    ListNetworkListsResponse:
      properties:
        count:
          format: int64
          type: integer
        total_pages:
          format: int64
          type: integer
        schema_version:
          format: int64
          type: integer
        links:
          $ref: '#/components/schemas/Links'
        results:
          items:
            $ref: '#/components/schemas/NetworkLists'
          type: array
      type: object
    NetworkListResponseEntry:
      properties:
        id:
          format: int64
          type: integer
          example: 1614
        last_editor:
          type: string
          example: Azion
        last_modified:
          type: string
          example: 2023-08-10T05:00:07.893747Z
        list_type:
          type: string
          example: ip_cidr
        name:
          type: string
          example: Network List created using the API
        items_values:
          type: array
          items:
            type: string
          example:
            - 192.168.0.1
      type: object
    NetworkListUuidResponseEntry:
        oneOf:
        - $ref: '#/components/schemas/NetworkListUuidResponseEntryString'
        - $ref: '#/components/schemas/NetworkListUuidResponseEntryInt'
    NetworkListUuidResponseEntryString:
      properties:
        last_editor:
          type: string
          example: Azion
        last_modified:
          type: string
          example: 2023-08-10T05:00:07.893747Z
        list_type:
          type: string
          example: ip_cidr
        name:
          type: string
          example: Network List created using the API
        items_values:
          type: array
          items:
            type: string
          example:
            - 192.168.0.1
      type: object
    NetworkListUuidResponseEntryInt:
      properties:
        last_editor:
          type: string
          example: Azion
        last_modified:
          type: string
          example: 2023-08-10T05:00:07.893747Z
        list_type:
          type: string
          example: asn
        name:
          type: string
          example: Network List created using the API
        items_values:
          type: array
          items:
            type: integer
          example:
            - 1234
      type: object
    CreateNetworkListsRequest:
      properties:
        name:
          type: string
          example: Network List created using the API
        items_values:
          type: array
          items:
            type: string
          example:
            - 192.168.0.1
        list_type:
          type: string
          enum: [ip_cidr, asn, countries]
          example: ip_cidr
      type: object
    BadRequestResponse:
      properties:
        name:
          type: array
          items:
            type: string
        items_values:
          type: array
          items:
            type: string
        list_type:
          type: array
          items:
            type: string
      type: object
    NetworkListsResponse:
      properties:
        results:
          $ref: '#/components/schemas/NetworkListResponseEntry'
        schema_version:
          format: int64
          type: integer
          example: 3
      type: object
    NetworkListUuidResponse:
      properties:
        results:
          $ref: '#/components/schemas/NetworkListUuidResponseEntry'
        schema_version:
          format: int64
          type: integer
          example: 3
      type: object
  securitySchemes:
    tokenAuth:
      type: apiKey
      name: Authorization
      in: header
      description: |
        You must inform a token to auth.
        Usage format: `Token <TOKEN>`