components:
  schemas:
    PurgeUrlRequest:
      type: object
      additionalProperties: false
      properties:
        urls:
          type: array
          items:
            type: string
        method:
          type: string
      required:
      - urls
      - method
      example:
        urls:
          - http://www.domain.com/
          - http://www.domain.com/test.js
          - http://static.mistaken-domain.com/image1.jpg
        method: delete
    PurgeCacheKeyRequest:
      type: object
      additionalProperties: false
      properties:
        urls:
          type: array
          items:
            type: string
        method:
          type: string
        layer:
          type: string
      required:
      - urls
      - method
      - layer
      example:
        urls:
          - http://www.domain.com/@@cookie_name=cookie_value
          - http://www.domain.com/test.js
          - http://static.domain.com/image1.jpg?ims=arguments@@variants
        method: delete
        layer: l2_caching
    PurgeWildcardRequest:
      type: object
      additionalProperties: false
      properties:
        urls:
          type: array
          items:
            type: string
        method:
          type: string
      required:
      - urls
      - method
      example:
        urls:
          - http://www.domain.com/path/image.jpg*
        method: delete
  securitySchemes:
    JWT:
      description: |
        You must inform a token to auth.
        Usage format: `Token <TOKEN>`
      in: header
      name: Authorization
      type: apiKey
info:
  title: Purge API
  description: Azion Real-Time Purge
  version: 1.0.0
openapi: 3.0.0
tags:
  - name: Real-Time Purge
    description: >-
      If you need to delete an object from the Edge Caching or L2 Caching layers
      before time-out, you can use the Real-Time Purge API. 

      If desired, integrate the Azion API with your CMS to automate any content
      update process.
paths:
  /purge/url:
    post:
      operationId: purgeUrl
      tags:
        - Real-Time Purge
      summary: /purge/url
      description: >-
        List of URLs you want to remove from the Azion Edge Servers cache.


        urls (array): list of up to 50 URLs to be expired from the cache, per
        request.


        method (choice): purge method, use the “delete” value for removal.
      requestBody:
        content:
          application/json; version=3:
            schema:
              $ref: '#/components/schemas/PurgeUrlRequest'
      security:
        - JWT: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json; version=3
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json; version=3: {}
        '201':
          description: Created
          content:
            application/json; version=3: {}
        '204':
          description: No Content
          content:
            application/json; version=3: {}
        '207':
          description: Multi Status
          content:
            application/json; version=3: {}
        '400':
          description: Bad Request
          content:
            application/json; version=3: {}
        '401':
          description: Unauthorized
          content:
            application/json; version=3: {}
        '403':
          description: Forbidden
          content:
            application/json; version=3: {}
        '404':
          description: Not Found
          content:
            application/json; version=3: {}
        '405':
          description: Method Not Allowed
          content:
            application/json; version=3: {}
        '406':
          description: Not Acceptable
          content:
            application/json; version=3: {}
        '409':
          description: Conflict
          content:
            application/json; version=3: {}
        '429':
          description: Too Many Requests
          content:
            application/json; version=3: {}
        '500':
          description: Internal Server Error
          content:
            application/json; version=3: {}
  /purge/cachekey:
    post:
      operationId: purgeCacheKey
      tags:
        - Real-Time Purge
      summary: /purge/cachekey
      description: >-
        List of Cache Keys you want to remove from the Azion Edge Servers cache.


        urls (array): list of up to 50 Cache Keys to be expired from the cache,
        per request.


        method (choice): purge method, use the “delete” value for removal.


        Layer (choice): layer where the purge will be done. Use the value
        “edge_caching” (default value if not informed) to purge on the Edge
        Caching layer and the value “l2_caching” to purge on L2 Caching.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurgeCacheKeyRequest'
      security:
        - JWT: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json; version=3
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
        '201':
          description: Created
          content:
            application/json; version=3: {}
        '204':
          description: No Content
          content:
            application/json; version=3: {}
        '207':
          description: Multi Status
          content:
            application/json; version=3: {}
        '400':
          description: Bad Request
          content:
            application/json; version=3: {}
        '401':
          description: Unauthorized
          content:
            application/json; version=3: {}
        '403':
          description: Forbidden
          content:
            application/json; version=3: {}
        '404':
          description: Not Found
          content:
            application/json; version=3: {}
        '405':
          description: Method Not Allowed
          content:
            application/json; version=3: {}
        '406':
          description: Not Acceptable
          content:
            application/json; version=3: {}
        '409':
          description: Conflict
          content:
            application/json; version=3: {}
        '429':
          description: Too Many Requests
          content:
            application/json; version=3: {}
        '500':
          description: Internal Server Error
          content:
            application/json; version=3: {}
  /purge/wildcard:
    post:
      operationId: purgeWildcard
      tags:
        - Real-Time Purge
      summary: /purge/wildcard
      description: >-
        The Wildcard expression that represents the list of objects that you
        want to remove from the Azion Edge Servers cache.


        urls (array):the Wildcard URL or Wildcard Cache Key that represents the
        list of objects you want to expire. You can only use one Wildcard
        expression per request.


        method (choice): purge method, use the “delete” value for removal.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurgeWildcardRequest'
      security:
        - JWT: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json; version=3
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
        '201':
          description: Created
          content:
            application/json; version=3: {}
        '204':
          description: No Content
          content:
            application/json; version=3: {}
        '207':
          description: Multi Status
          content:
            application/json; version=3: {}
        '400':
          description: Bad Request
          content:
            application/json; version=3: {}
        '401':
          description: Unauthorized
          content:
            application/json; version=3: {}
        '403':
          description: Forbidden
          content:
            application/json; version=3: {}
        '404':
          description: Not Found
          content:
            application/json; version=3: {}
        '405':
          description: Method Not Allowed
          content:
            application/json; version=3: {}
        '406':
          description: Not Acceptable
          content:
            application/json; version=3: {}
        '409':
          description: Conflict
          content:
            application/json; version=3: {}
        '429':
          description: Too Many Requests
          content:
            application/json; version=3: {}
        '500':
          description: Internal Server Error
          content:
            application/json; version=3: {}
servers:
- description: Local Dev
  url: http://localhost:3002
- description: Staging
  url: https://stage-api.azion.net
- description: Production
  url: https://api.azionapi.net
