/*
Edgenode API

Azion Orchestration

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgenode

import (
	"encoding/json"
)

// checks if the EdgeNodeResponseWithTotal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EdgeNodeResponseWithTotal{}

// EdgeNodeResponseWithTotal struct for EdgeNodeResponseWithTotal
type EdgeNodeResponseWithTotal struct {
	Nodes []EdgeNodeResponse `json:"nodes"`
	Total int64 `json:"total"`
}

// NewEdgeNodeResponseWithTotal instantiates a new EdgeNodeResponseWithTotal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEdgeNodeResponseWithTotal(nodes []EdgeNodeResponse, total int64) *EdgeNodeResponseWithTotal {
	this := EdgeNodeResponseWithTotal{}
	this.Nodes = nodes
	this.Total = total
	return &this
}

// NewEdgeNodeResponseWithTotalWithDefaults instantiates a new EdgeNodeResponseWithTotal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEdgeNodeResponseWithTotalWithDefaults() *EdgeNodeResponseWithTotal {
	this := EdgeNodeResponseWithTotal{}
	return &this
}

// GetNodes returns the Nodes field value
func (o *EdgeNodeResponseWithTotal) GetNodes() []EdgeNodeResponse {
	if o == nil {
		var ret []EdgeNodeResponse
		return ret
	}

	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value
// and a boolean to check if the value has been set.
func (o *EdgeNodeResponseWithTotal) GetNodesOk() ([]EdgeNodeResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Nodes, true
}

// SetNodes sets field value
func (o *EdgeNodeResponseWithTotal) SetNodes(v []EdgeNodeResponse) {
	o.Nodes = v
}

// GetTotal returns the Total field value
func (o *EdgeNodeResponseWithTotal) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *EdgeNodeResponseWithTotal) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *EdgeNodeResponseWithTotal) SetTotal(v int64) {
	o.Total = v
}

func (o EdgeNodeResponseWithTotal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EdgeNodeResponseWithTotal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nodes"] = o.Nodes
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

type NullableEdgeNodeResponseWithTotal struct {
	value *EdgeNodeResponseWithTotal
	isSet bool
}

func (v NullableEdgeNodeResponseWithTotal) Get() *EdgeNodeResponseWithTotal {
	return v.value
}

func (v *NullableEdgeNodeResponseWithTotal) Set(val *EdgeNodeResponseWithTotal) {
	v.value = val
	v.isSet = true
}

func (v NullableEdgeNodeResponseWithTotal) IsSet() bool {
	return v.isSet
}

func (v *NullableEdgeNodeResponseWithTotal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEdgeNodeResponseWithTotal(val *EdgeNodeResponseWithTotal) *NullableEdgeNodeResponseWithTotal {
	return &NullableEdgeNodeResponseWithTotal{value: val, isSet: true}
}

func (v NullableEdgeNodeResponseWithTotal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEdgeNodeResponseWithTotal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


