/*
Edgenode API

Azion Orchestration

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgenode

import (
	"encoding/json"
	"time"
)

// checks if the ServiceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceResponse{}

// ServiceResponse struct for ServiceResponse
type ServiceResponse struct {
	BindId int64 `json:"bind_id"`
	IsBound int64 `json:"is_bound"`
	LastEditor string `json:"last_editor"`
	Name string `json:"name"`
	ServiceId int64 `json:"service_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// NewServiceResponse instantiates a new ServiceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceResponse(bindId int64, isBound int64, lastEditor string, name string, serviceId int64, updatedAt time.Time) *ServiceResponse {
	this := ServiceResponse{}
	this.BindId = bindId
	this.IsBound = isBound
	this.LastEditor = lastEditor
	this.Name = name
	this.ServiceId = serviceId
	this.UpdatedAt = updatedAt
	return &this
}

// NewServiceResponseWithDefaults instantiates a new ServiceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceResponseWithDefaults() *ServiceResponse {
	this := ServiceResponse{}
	return &this
}

// GetBindId returns the BindId field value
func (o *ServiceResponse) GetBindId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.BindId
}

// GetBindIdOk returns a tuple with the BindId field value
// and a boolean to check if the value has been set.
func (o *ServiceResponse) GetBindIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BindId, true
}

// SetBindId sets field value
func (o *ServiceResponse) SetBindId(v int64) {
	o.BindId = v
}

// GetIsBound returns the IsBound field value
func (o *ServiceResponse) GetIsBound() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.IsBound
}

// GetIsBoundOk returns a tuple with the IsBound field value
// and a boolean to check if the value has been set.
func (o *ServiceResponse) GetIsBoundOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsBound, true
}

// SetIsBound sets field value
func (o *ServiceResponse) SetIsBound(v int64) {
	o.IsBound = v
}

// GetLastEditor returns the LastEditor field value
func (o *ServiceResponse) GetLastEditor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastEditor
}

// GetLastEditorOk returns a tuple with the LastEditor field value
// and a boolean to check if the value has been set.
func (o *ServiceResponse) GetLastEditorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastEditor, true
}

// SetLastEditor sets field value
func (o *ServiceResponse) SetLastEditor(v string) {
	o.LastEditor = v
}

// GetName returns the Name field value
func (o *ServiceResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServiceResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServiceResponse) SetName(v string) {
	o.Name = v
}

// GetServiceId returns the ServiceId field value
func (o *ServiceResponse) GetServiceId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *ServiceResponse) GetServiceIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *ServiceResponse) SetServiceId(v int64) {
	o.ServiceId = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ServiceResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ServiceResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ServiceResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o ServiceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bind_id"] = o.BindId
	toSerialize["is_bound"] = o.IsBound
	toSerialize["last_editor"] = o.LastEditor
	toSerialize["name"] = o.Name
	toSerialize["service_id"] = o.ServiceId
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

type NullableServiceResponse struct {
	value *ServiceResponse
	isSet bool
}

func (v NullableServiceResponse) Get() *ServiceResponse {
	return v.value
}

func (v *NullableServiceResponse) Set(val *ServiceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceResponse(val *ServiceResponse) *NullableServiceResponse {
	return &NullableServiceResponse{value: val, isSet: true}
}

func (v NullableServiceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


