/*
Edgenode API

Azion Orchestration

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgenode

import (
	"encoding/json"
)

// checks if the UpdateServiceBindRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateServiceBindRequest{}

// UpdateServiceBindRequest struct for UpdateServiceBindRequest
type UpdateServiceBindRequest struct {
	Variables []Variable `json:"variables"`
}

// NewUpdateServiceBindRequest instantiates a new UpdateServiceBindRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateServiceBindRequest(variables []Variable) *UpdateServiceBindRequest {
	this := UpdateServiceBindRequest{}
	this.Variables = variables
	return &this
}

// NewUpdateServiceBindRequestWithDefaults instantiates a new UpdateServiceBindRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateServiceBindRequestWithDefaults() *UpdateServiceBindRequest {
	this := UpdateServiceBindRequest{}
	return &this
}

// GetVariables returns the Variables field value
func (o *UpdateServiceBindRequest) GetVariables() []Variable {
	if o == nil {
		var ret []Variable
		return ret
	}

	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value
// and a boolean to check if the value has been set.
func (o *UpdateServiceBindRequest) GetVariablesOk() ([]Variable, bool) {
	if o == nil {
		return nil, false
	}
	return o.Variables, true
}

// SetVariables sets field value
func (o *UpdateServiceBindRequest) SetVariables(v []Variable) {
	o.Variables = v
}

func (o UpdateServiceBindRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateServiceBindRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["variables"] = o.Variables
	return toSerialize, nil
}

type NullableUpdateServiceBindRequest struct {
	value *UpdateServiceBindRequest
	isSet bool
}

func (v NullableUpdateServiceBindRequest) Get() *UpdateServiceBindRequest {
	return v.value
}

func (v *NullableUpdateServiceBindRequest) Set(val *UpdateServiceBindRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateServiceBindRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateServiceBindRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateServiceBindRequest(val *UpdateServiceBindRequest) *NullableUpdateServiceBindRequest {
	return &NullableUpdateServiceBindRequest{value: val, isSet: true}
}

func (v NullableUpdateServiceBindRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateServiceBindRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


