/*
Edgenode API

Azion Orchestration

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgenode

import (
	"encoding/json"
)

// checks if the ServiceBindRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceBindRequest{}

// ServiceBindRequest struct for ServiceBindRequest
type ServiceBindRequest struct {
	ServiceId int64 `json:"service_id"`
	Variables []Variable `json:"variables"`
}

// NewServiceBindRequest instantiates a new ServiceBindRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceBindRequest(serviceId int64, variables []Variable) *ServiceBindRequest {
	this := ServiceBindRequest{}
	this.ServiceId = serviceId
	this.Variables = variables
	return &this
}

// NewServiceBindRequestWithDefaults instantiates a new ServiceBindRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceBindRequestWithDefaults() *ServiceBindRequest {
	this := ServiceBindRequest{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *ServiceBindRequest) GetServiceId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *ServiceBindRequest) GetServiceIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *ServiceBindRequest) SetServiceId(v int64) {
	o.ServiceId = v
}

// GetVariables returns the Variables field value
func (o *ServiceBindRequest) GetVariables() []Variable {
	if o == nil {
		var ret []Variable
		return ret
	}

	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value
// and a boolean to check if the value has been set.
func (o *ServiceBindRequest) GetVariablesOk() ([]Variable, bool) {
	if o == nil {
		return nil, false
	}
	return o.Variables, true
}

// SetVariables sets field value
func (o *ServiceBindRequest) SetVariables(v []Variable) {
	o.Variables = v
}

func (o ServiceBindRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceBindRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["service_id"] = o.ServiceId
	toSerialize["variables"] = o.Variables
	return toSerialize, nil
}

type NullableServiceBindRequest struct {
	value *ServiceBindRequest
	isSet bool
}

func (v NullableServiceBindRequest) Get() *ServiceBindRequest {
	return v.value
}

func (v *NullableServiceBindRequest) Set(val *ServiceBindRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceBindRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceBindRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceBindRequest(val *ServiceBindRequest) *NullableServiceBindRequest {
	return &NullableServiceBindRequest{value: val, isSet: true}
}

func (v NullableServiceBindRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceBindRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


