/*
Edgenode API

Azion Orchestration

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package edgenode

import (
	"encoding/json"
)

// checks if the NodeGroupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodeGroupResponse{}

// NodeGroupResponse struct for NodeGroupResponse
type NodeGroupResponse struct {
	Id int64 `json:"id"`
	Name string `json:"name"`
}

// NewNodeGroupResponse instantiates a new NodeGroupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeGroupResponse(id int64, name string) *NodeGroupResponse {
	this := NodeGroupResponse{}
	this.Id = id
	this.Name = name
	return &this
}

// NewNodeGroupResponseWithDefaults instantiates a new NodeGroupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeGroupResponseWithDefaults() *NodeGroupResponse {
	this := NodeGroupResponse{}
	return &this
}

// GetId returns the Id field value
func (o *NodeGroupResponse) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NodeGroupResponse) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NodeGroupResponse) SetId(v int64) {
	o.Id = v
}

// GetName returns the Name field value
func (o *NodeGroupResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NodeGroupResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NodeGroupResponse) SetName(v string) {
	o.Name = v
}

func (o NodeGroupResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodeGroupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableNodeGroupResponse struct {
	value *NodeGroupResponse
	isSet bool
}

func (v NullableNodeGroupResponse) Get() *NodeGroupResponse {
	return v.value
}

func (v *NullableNodeGroupResponse) Set(val *NodeGroupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeGroupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeGroupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeGroupResponse(val *NodeGroupResponse) *NullableNodeGroupResponse {
	return &NullableNodeGroupResponse{value: val, isSet: true}
}

func (v NullableNodeGroupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeGroupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


