extends: .spectral.yaml
overrides:
  - files:
      - "variables.yaml#/paths/~1variables"
      - "variables.yaml#/paths/~1variables~1%7Buuid%7D"
    rules:
      azion-mandatory-status-codes: "off"
  - files:
      - "variables.yaml#/components/schemas/Variable/properties/key"
      - "variables.yaml#/components/schemas/Variable/properties/value"
      - "variables.yaml#/components/schemas/VariableCreate/properties/key"
      - "variables.yaml#/components/schemas/VariableCreate/properties/value"
      - "variables.yaml#/components/schemas/VariableGet/properties/key"
    rules:
      azion-string-pattern-properties-rule: "off"