extends: .spectral.yaml
overrides:
  - files:
      - "idns.yaml#/paths/~1intelligent_dns"
      - "idns.yaml#/paths/~1intelligent_dns~1%7Bzone_id%7D"
      - "idns.yaml#/paths/~1intelligent_dns~1%7Bzone_id%7D~1dnssec"
      - "idns.yaml#/paths/~1intelligent_dns~1%7Bzone_id%7D~1records"
      - "idns.yaml#/paths/~1intelligent_dns~1%7Bzone_id%7D~1records~1%7Brecord_id%7D"
    rules:
      azion-mandatory-status-codes: "off"
  - files:
      - "idns.yaml#/components/schemas/Zone/properties/id"
      - "idns.yaml#/components/schemas/GetZonesResponse/properties/schema_version"
      - "idns.yaml#/components/schemas/GetZonesResponse/properties/count"
      - "idns.yaml#/components/schemas/GetZonesResponse/properties/total_pages"
      - "idns.yaml#/components/schemas/GetZoneResponse/properties/schema_version"
      - "idns.yaml#/components/schemas/PostOrPutZoneResponse/properties/schema_version"
      - "idns.yaml#/components/schemas/RecordGet/properties/record_id"
      - "idns.yaml#/components/schemas/RecordGet/properties/weight"
      - "idns.yaml#/components/schemas/RecordGet/properties/ttl"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/id"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/weight"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/ttl"
      - "idns.yaml#/components/schemas/GetRecordsResponse/properties/schema_version"
      - "idns.yaml#/components/schemas/GetRecordsResponse/properties/count"
      - "idns.yaml#/components/schemas/GetRecordsResponse/properties/total_pages"
      - "idns.yaml#/components/schemas/PostOrPutRecordResponse/properties/schema_version"
      - "idns.yaml#/components/schemas/GetOrPatchDnsSecResponse/properties/schema_version"
      - "idns.yaml#/components/schemas/GetRecordsResponse_results/properties/zone_id"
      - "idns.yaml#/components/schemas/DnsSec_delegation_signer_digest_type/properties/id"
    rules:
      azion-number-minimum-limit-rule: "off"
  - files:
      - "idns.yaml#/components/schemas/Zone/properties/id"
      - "idns.yaml#/components/schemas/GetZonesResponse/properties/schema_version"
      - "idns.yaml#/components/schemas/GetZonesResponse/properties/count"
      - "idns.yaml#/components/schemas/GetZonesResponse/properties/total_pages"
      - "idns.yaml#/components/schemas/GetZoneResponse/properties/schema_version"
      - "idns.yaml#/components/schemas/PostOrPutZoneResponse/properties/schema_version"
      - "idns.yaml#/components/schemas/RecordGet/properties/record_id"
      - "idns.yaml#/components/schemas/RecordGet/properties/weight"
      - "idns.yaml#/components/schemas/RecordGet/properties/ttl"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/id"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/weight"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/ttl"
      - "idns.yaml#/components/schemas/GetRecordsResponse/properties/schema_version"
      - "idns.yaml#/components/schemas/GetRecordsResponse/properties/count"
      - "idns.yaml#/components/schemas/GetRecordsResponse/properties/total_pages"
      - "idns.yaml#/components/schemas/PostOrPutRecordResponse/properties/schema_version"
      - "idns.yaml#/components/schemas/GetOrPatchDnsSecResponse/properties/schema_version"
      - "idns.yaml#/components/schemas/GetRecordsResponse_results/properties/zone_id"
      - "idns.yaml#/components/schemas/DnsSec_delegation_signer_digest_type/properties/id"
    rules:
      azion-number-maximum-limit-rule: "off"
  - files:
      - "idns.yaml#/components/schemas/Zone/properties/name"
      - "idns.yaml#/components/schemas/Zone/properties/domain"
      - "idns.yaml#/components/schemas/RecordGet/properties/entry"
      - "idns.yaml#/components/schemas/RecordGet/properties/description"
      - "idns.yaml#/components/schemas/RecordGet/properties/policy"
      - "idns.yaml#/components/schemas/RecordGet/properties/record_type"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/entry"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/description"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/policy"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/record_type"
      - "idns.yaml#/components/schemas/ErrorResponse/properties/detail"
      - "idns.yaml#/components/schemas/GetRecordsResponse_results/properties/zone_domain"
      - "idns.yaml#/components/schemas/DnsSec_delegation_signer_digest_type/properties/slug"
      - "idns.yaml#/components/schemas/DnsSec_delegation_signer/properties/digest"
    rules:
      azion-string-minlength-properties-rule: "off"
  - files:
      - "idns.yaml#/components/schemas/Zone/properties/name"
      - "idns.yaml#/components/schemas/Zone/properties/domain"
      - "idns.yaml#/components/schemas/RecordGet/properties/entry"
      - "idns.yaml#/components/schemas/RecordGet/properties/description"
      - "idns.yaml#/components/schemas/RecordGet/properties/policy"
      - "idns.yaml#/components/schemas/RecordGet/properties/record_type"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/entry"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/description"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/policy"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/record_type"
      - "idns.yaml#/components/schemas/ErrorResponse/properties/detail"
      - "idns.yaml#/components/schemas/GetZonesResponse_links/properties/previous"
      - "idns.yaml#/components/schemas/GetZonesResponse_links/properties/next"
      - "idns.yaml#/components/schemas/GetRecordsResponse_results/properties/zone_domain"
      - "idns.yaml#/components/schemas/DnsSec_delegation_signer_digest_type/properties/slug"
      - "idns.yaml#/components/schemas/DnsSec_delegation_signer/properties/digest"
    rules:
      azion-string-maxlength-properties-rule: "off"
  - files:
      - "idns.yaml#/components/schemas/Zone/properties/name"
      - "idns.yaml#/components/schemas/Zone/properties/domain"
      - "idns.yaml#/components/schemas/RecordGet/properties/entry"
      - "idns.yaml#/components/schemas/RecordGet/properties/description"
      - "idns.yaml#/components/schemas/RecordGet/properties/policy"
      - "idns.yaml#/components/schemas/RecordGet/properties/record_type"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/entry"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/description"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/policy"
      - "idns.yaml#/components/schemas/RecordPostOrPut/properties/record_type"
      - "idns.yaml#/components/schemas/ErrorResponse/properties/detail"
      - "idns.yaml#/components/schemas/GetZonesResponse_links/properties/previous"
      - "idns.yaml#/components/schemas/GetZonesResponse_links/properties/next"
      - "idns.yaml#/components/schemas/GetRecordsResponse_results/properties/zone_domain"
      - "idns.yaml#/components/schemas/DnsSec_delegation_signer_digest_type/properties/slug"
      - "idns.yaml#/components/schemas/DnsSec_delegation_signer/properties/digest"
    rules:
      azion-string-pattern-properties-rule: "off"