extends: .spectral.yaml
overrides:
  - files:
      - "edgefirewall.yaml#/paths/~1edge_firewall"
      - "edgefirewall.yaml#/paths/~1edge_firewall~1%7Buuid%7D"
      - "edgefirewall.yaml#/paths/~1edge_firewall~1%7Bedge_firewall_id%7D~1rules_engine"
      - "edgefirewall.yaml#/paths/~1edge_firewall~1%7Bedge_firewall_id%7D~1rules_engine~1%7Brule_set_id%7D"
    rules:
      azion-mandatory-status-codes: "off"
  - files:
      - "edgefirewall.yaml#/components/schemas/EdgeFirewall/properties/id"
      - "edgefirewall.yaml#/components/schemas/ListEdgeFirewallResponse/properties/count"
      - "edgefirewall.yaml#/components/schemas/ListEdgeFirewallResponse/properties/total_pages"
      - "edgefirewall.yaml#/components/schemas/ListEdgeFirewallResponse/properties/schema_version"
      - "edgefirewall.yaml#/components/schemas/EdgeFirewallResponse/properties/schema_version"
      - "edgefirewall.yaml#/components/schemas/RuleSetResponseAll/properties/schema_version"
    rules:
      azion-number-minimum-limit-rule: "off"
  - files:
      - "edgefirewall.yaml#/components/schemas/EdgeFirewall/properties/id"
      - "edgefirewall.yaml#/components/schemas/ListEdgeFirewallResponse/properties/count"
      - "edgefirewall.yaml#/components/schemas/ListEdgeFirewallResponse/properties/total_pages"
      - "edgefirewall.yaml#/components/schemas/ListEdgeFirewallResponse/properties/schema_version"
      - "edgefirewall.yaml#/components/schemas/EdgeFirewallResponse/properties/schema_version"
      - "edgefirewall.yaml#/components/schemas/RuleSetResult/properties/schema_version"
      - "edgefirewall.yaml#/components/schemas/RuleSetResultAll/properties/id"
      - "edgefirewall.yaml#/components/schemas/RuleSetResultAll/properties/order"
      - "edgefirewall.yaml#/components/schemas/RuleSetResponse/properties/id"
      - "edgefirewall.yaml#/components/schemas/RuleSetResponse/properties/order"
      - "edgefirewall.yaml#/components/schemas/RuleSetResponseAll/properties/count"
      - "edgefirewall.yaml#/components/schemas/RuleSetResponseAll/properties/total_pages"
      - "edgefirewall.yaml#/components/schemas/RuleSetResponseAll/properties/schema_version"
    rules:
      azion-number-maximum-limit-rule: "off"
  - files:
      - "edgefirewall.yaml#/components/schemas/EdgeFirewall/properties/name"
      - "edgefirewall.yaml#/components/schemas/EdgeFirewall/properties/last_editor"
      - "edgefirewall.yaml#/components/schemas/EdgeFirewall/properties/last_modified"
      - "edgefirewall.yaml#/components/schemas/CreateEdgeFirewallRequest/properties/name"
      - "edgefirewall.yaml#/components/schemas/UpdateEdgeFirewallRequest/properties/name"
      - "edgefirewall.yaml#/components/schemas/RuleSetResultAll/properties/name"
      - "edgefirewall.yaml#/components/schemas/RuleSetResultAll/properties/description"
      - "edgefirewall.yaml#/components/schemas/CreateRuleSetRequest/properties/name"
      - "edgefirewall.yaml#/components/schemas/RuleSetResponse/properties/name"
    rules:
      azion-string-minlength-properties-rule: "off"
  - files:
      - "edgefirewall.yaml#/components/schemas/Links/properties/previous"
      - "edgefirewall.yaml#/components/schemas/Links/properties/next"
      - "edgefirewall.yaml#/components/schemas/EdgeFirewall/properties/name"
      - "edgefirewall.yaml#/components/schemas/EdgeFirewall/properties/last_editor"
      - "edgefirewall.yaml#/components/schemas/EdgeFirewall/properties/last_modified"
      - "edgefirewall.yaml#/components/schemas/CreateEdgeFirewallRequest/properties/name"
      - "edgefirewall.yaml#/components/schemas/UpdateEdgeFirewallRequest/properties/name"
      - "edgefirewall.yaml#/components/schemas/RuleSetResultAll/properties/name"
      - "edgefirewall.yaml#/components/schemas/RuleSetResultAll/properties/description"
      - "edgefirewall.yaml#/components/schemas/CreateRuleSetRequest/properties/name"
      - "edgefirewall.yaml#/components/schemas/RuleSetResponse/properties/name"
    rules:
      azion-string-maxlength-properties-rule: "off"
  - files:
      - "edgefirewall.yaml#/components/schemas/Links/properties/previous"
      - "edgefirewall.yaml#/components/schemas/Links/properties/next"
      - "edgefirewall.yaml#/components/schemas/EdgeFirewall/properties/name"
      - "edgefirewall.yaml#/components/schemas/EdgeFirewall/properties/last_editor"
      - "edgefirewall.yaml#/components/schemas/EdgeFirewall/properties/last_modified"
      - "edgefirewall.yaml#/components/schemas/CreateEdgeFirewallRequest/properties/name"
      - "edgefirewall.yaml#/components/schemas/UpdateEdgeFirewallRequest/properties/name"
      - "edgefirewall.yaml#/components/schemas/RuleSetResultAll/properties/name"
      - "edgefirewall.yaml#/components/schemas/RuleSetResultAll/properties/description"
      - "edgefirewall.yaml#/components/schemas/CreateRuleSetRequest/properties/name"
      - "edgefirewall.yaml#/components/schemas/RuleSetResponse/properties/name"
    rules:
      azion-string-pattern-properties-rule: "off"