extends: .spectral.yaml
overrides:
  - files:
      - "domains.yaml#/paths/~1domains"
      - "domains.yaml#/paths/~1domains~1%7Bid%7D"
    rules:
      azion-mandatory-status-codes: "off"
  - files:
      - "domains.yaml#/components/schemas/CreateDomainRequest/properties/edge_application_id"
      - "domains.yaml#/components/schemas/UpdateDomainRequest/properties/edge_application_id"
      - "domains.yaml#/components/schemas/PutDomainRequest/properties/edge_application_id"
      - "domains.yaml#/components/schemas/DomainResponseWithResults/properties/count"
      - "domains.yaml#/components/schemas/DomainResponseWithResults/properties/total_pages"
      - "domains.yaml#/components/schemas/DomainResponseWithResults/properties/schema_version"
      - "domains.yaml#/components/schemas/DomainResponseWithResult/properties/count"
      - "domains.yaml#/components/schemas/DomainResponseWithResult/properties/total_pages"
      - "domains.yaml#/components/schemas/DomainResponseWithResult/properties/schema_version"
      - "domains.yaml#/components/schemas/DomainResults/properties/id"
      - "domains.yaml#/components/schemas/DomainResults/properties/edge_application_id"
    rules:
      azion-number-minimum-limit-rule: "off"
  - files:
      - "domains.yaml#/components/schemas/CreateDomainRequest/properties/edge_application_id"
      - "domains.yaml#/components/schemas/UpdateDomainRequest/properties/edge_application_id"
      - "domains.yaml#/components/schemas/PutDomainRequest/properties/edge_application_id"
      - "domains.yaml#/components/schemas/DomainResponseWithResults/properties/count"
      - "domains.yaml#/components/schemas/DomainResponseWithResults/properties/total_pages"
      - "domains.yaml#/components/schemas/DomainResponseWithResults/properties/schema_version"
      - "domains.yaml#/components/schemas/DomainResponseWithResult/properties/count"
      - "domains.yaml#/components/schemas/DomainResponseWithResult/properties/total_pages"
      - "domains.yaml#/components/schemas/DomainResponseWithResult/properties/schema_version"
      - "domains.yaml#/components/schemas/DomainResults/properties/id"
      - "domains.yaml#/components/schemas/DomainResults/properties/edge_application_id"
    rules:
      azion-number-maximum-limit-rule: "off"
  - files:
      - "domains.yaml#/components/schemas/CreateDomainRequest/properties/name"
      - "domains.yaml#/components/schemas/UpdateDomainRequest/properties/name"
      - "domains.yaml#/components/schemas/PutDomainRequest/properties/name"
      - "domains.yaml#/components/schemas/DomainResults/properties/name"
      - "domains.yaml#/components/schemas/DomainResults/properties/domain_name"
      - "domains.yaml#/components/schemas/DomainResults/properties/environment"
    rules:
      azion-string-minlength-properties-rule: "off"
  - files:
      - "domains.yaml#/components/schemas/CreateDomainRequest/properties/name"
      - "domains.yaml#/components/schemas/UpdateDomainRequest/properties/name"
      - "domains.yaml#/components/schemas/PutDomainRequest/properties/name"
      - "domains.yaml#/components/schemas/DomainLinks/properties/previous"
      - "domains.yaml#/components/schemas/DomainLinks/properties/next"
      - "domains.yaml#/components/schemas/DomainResults/properties/name"
      - "domains.yaml#/components/schemas/DomainResults/properties/domain_name"
      - "domains.yaml#/components/schemas/DomainResults/properties/environment"
      - "domains.yaml#/components/schemas/DomainResults/properties/mtls_trusted_ca_certificate_id"
      - "domains.yaml#/components/schemas/DomainResults/properties/mtls_verification"
    rules:
      azion-string-maxlength-properties-rule: "off"
  - files:
      - "domains.yaml#/components/schemas/CreateDomainRequest/properties/name"
      - "domains.yaml#/components/schemas/UpdateDomainRequest/properties/name"
      - "domains.yaml#/components/schemas/PutDomainRequest/properties/name"
      - "domains.yaml#/components/schemas/DomainLinks/properties/previous"
      - "domains.yaml#/components/schemas/DomainLinks/properties/next"
      - "domains.yaml#/components/schemas/DomainResults/properties/name"
      - "domains.yaml#/components/schemas/DomainResults/properties/domain_name"
      - "domains.yaml#/components/schemas/DomainResults/properties/environment"
      - "domains.yaml#/components/schemas/DomainResults/properties/mtls_trusted_ca_certificate_id"
      - "domains.yaml#/components/schemas/DomainResults/properties/mtls_verification"
    rules:
      azion-string-pattern-properties-rule: "off"