extends: .spectral.yaml
overrides:
  - files:
      - "realtimepurge.yaml#/components/schemas/PurgeUrlRequest/properties/method"
      - "realtimepurge.yaml#/components/schemas/PurgeCacheKeyRequest/properties/method"
      - "realtimepurge.yaml#/components/schemas/PurgeCacheKeyRequest/properties/layer"
      - "realtimepurge.yaml#/components/schemas/PurgeWildcardRequest/properties/method"
    rules:
      azion-string-minlength-properties-rule: "off"
  - files:
      - "realtimepurge.yaml#/components/schemas/PurgeUrlRequest/properties/method"
      - "realtimepurge.yaml#/components/schemas/PurgeCacheKeyRequest/properties/method"
      - "realtimepurge.yaml#/components/schemas/PurgeCacheKeyRequest/properties/layer"
      - "realtimepurge.yaml#/components/schemas/PurgeWildcardRequest/properties/method"
    rules:
      azion-string-maxlength-properties-rule: "off"
  - files:
      - "realtimepurge.yaml#/components/schemas/PurgeUrlRequest/properties/method"
      - "realtimepurge.yaml#/components/schemas/PurgeCacheKeyRequest/properties/method"
      - "realtimepurge.yaml#/components/schemas/PurgeCacheKeyRequest/properties/layer"
      - "realtimepurge.yaml#/components/schemas/PurgeWildcardRequest/properties/method"
    rules:
      azion-string-pattern-properties-rule: "off"