extends: .spectral.yaml
overrides:
  - files:
      - "personal_tokens.yaml#/components/schemas/PersonalTokenResponseWithResults/properties/count"
      - "personal_tokens.yaml#/components/schemas/PersonalTokenResponseWithResults/properties/total_pages"
      - "personal_tokens.yaml#/components/schemas/PersonalTokenResponseWithResults/properties/schema_version"
      - "personal_tokens.yaml#/components/schemas/CreatePersonalTokenResponse/properties/user_id"
    rules:
      azion-number-minimum-limit-rule: "off"
  - files:
      - "personal_tokens.yaml#/components/schemas/PersonalTokenResponseWithResults/properties/count"
      - "personal_tokens.yaml#/components/schemas/PersonalTokenResponseWithResults/properties/total_pages"
      - "personal_tokens.yaml#/components/schemas/PersonalTokenResponseWithResults/properties/schema_version"
      - "personal_tokens.yaml#/components/schemas/CreatePersonalTokenResponse/properties/user_id"
    rules:
      azion-number-maximum-limit-rule: "off"
  - files:
      - "personal_tokens.yaml#/components/schemas/PersonalTokenResponseGet/properties/name"
      - "personal_tokens.yaml#/components/schemas/CreatePersonalTokenRequest/properties/name"
      - "personal_tokens.yaml#/components/schemas/CreatePersonalTokenResponse/properties/name"
      - "personal_tokens.yaml#/components/schemas/CreatePersonalTokenResponse/properties/key"
    rules:
      azion-string-minlength-properties-rule: "off"
  - files:
      - "personal_tokens.yaml#/components/schemas/PersonalTokenResponseGet/properties/name"
      - "personal_tokens.yaml#/components/schemas/PersonalTokenResponseGet/properties/description"
      - "personal_tokens.yaml#/components/schemas/CreatePersonalTokenRequest/properties/name"
      - "personal_tokens.yaml#/components/schemas/CreatePersonalTokenRequest/properties/description"
      - "personal_tokens.yaml#/components/schemas/CreatePersonalTokenResponse/properties/name"
      - "personal_tokens.yaml#/components/schemas/CreatePersonalTokenResponse/properties/key"
      - "personal_tokens.yaml#/components/schemas/CreatePersonalTokenResponse/properties/description"
    rules:
      azion-string-maxlength-properties-rule: "off"
  - files:
      - "personal_tokens.yaml#/components/schemas/PersonalTokenResponseGet/properties/name"
      - "personal_tokens.yaml#/components/schemas/PersonalTokenResponseGet/properties/description"
      - "personal_tokens.yaml#/components/schemas/CreatePersonalTokenRequest/properties/name"
      - "personal_tokens.yaml#/components/schemas/CreatePersonalTokenRequest/properties/description"
      - "personal_tokens.yaml#/components/schemas/CreatePersonalTokenResponse/properties/name"
      - "personal_tokens.yaml#/components/schemas/CreatePersonalTokenResponse/properties/key"
      - "personal_tokens.yaml#/components/schemas/CreatePersonalTokenResponse/properties/description"
    rules:
      azion-string-pattern-properties-rule: "off"