extends: .spectral.yaml
overrides:
  - files:
      - "edgefunctionsinstance_edgefirewall.yaml#/paths/~1edge_firewall~1%7Bedge_firewall_id%7D~1functions_instances"
      - "edgefunctionsinstance_edgefirewall.yaml#/paths/~1edge_firewall~1%7Bedge_firewall_id%7D~1functions_instances~1%7Bedge_function_instance_id%7D"
    rules:
      azion-mandatory-status-codes: "off"
  - files:
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/EdgeFunctionsInstance/properties/id"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/EdgeFunctionsInstance/properties/edge_function"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/ListEdgeFunctionsInstancesResponse/properties/count"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/ListEdgeFunctionsInstancesResponse/properties/total_pages"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/ListEdgeFunctionsInstancesResponse/properties/schema_version"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/CreateEdgeFunctionsInstancesRequest/properties/edge_function"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/EdgeFunctionsInstanceResponse/properties/schema_version"
    rules:
      azion-number-minimum-limit-rule: "off"
  - files:
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/EdgeFunctionsInstance/properties/id"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/EdgeFunctionsInstance/properties/edge_function"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/ListEdgeFunctionsInstancesResponse/properties/count"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/ListEdgeFunctionsInstancesResponse/properties/total_pages"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/ListEdgeFunctionsInstancesResponse/properties/schema_version"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/CreateEdgeFunctionsInstancesRequest/properties/edge_function"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/EdgeFunctionsInstanceResponse/properties/schema_version"
    rules:
      azion-number-maximum-limit-rule: "off"
  - files:
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/Links/properties/previous"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/Links/properties/next"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/EdgeFunctionsInstance/properties/name"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/EdgeFunctionsInstance/properties/last_editor"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/EdgeFunctionsInstance/properties/last_modified"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/CreateEdgeFunctionsInstancesRequest/properties/name"
    rules:
      azion-string-minlength-properties-rule: "off"
  - files:
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/Links/properties/previous"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/Links/properties/next"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/EdgeFunctionsInstance/properties/name"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/EdgeFunctionsInstance/properties/last_editor"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/EdgeFunctionsInstance/properties/last_modified"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/CreateEdgeFunctionsInstancesRequest/properties/name"
    rules:
      azion-string-maxlength-properties-rule: "off"
  - files:
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/Links/properties/previous"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/Links/properties/next"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/EdgeFunctionsInstance/properties/name"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/EdgeFunctionsInstance/properties/last_editor"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/EdgeFunctionsInstance/properties/last_modified"
      - "edgefunctionsinstance_edgefirewall.yaml#/components/schemas/CreateEdgeFunctionsInstancesRequest/properties/name"
    rules:
      azion-string-pattern-properties-rule: "off"