extends: .spectral.yaml
overrides:
  - files:
      - "digital_certificates.yaml#/paths/~1digital_certificates"
      - "digital_certificates.yaml#/paths/~1digital_certificates~1csr"
      - "digital_certificates.yaml#/paths/~1digital_certificates~1%7Bdigital_certificate_id%7D"
    rules:
      azion-mandatory-status-codes: "off"
  - files:
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/id"
      - "digital_certificates.yaml#/components/schemas/DC200/properties/schema_version"
      - "digital_certificates.yaml#/components/schemas/DC200List/properties/count"
      - "digital_certificates.yaml#/components/schemas/DC200List/properties/total_pages"
      - "digital_certificates.yaml#/components/schemas/DC200List/properties/schema_version"
      - "digital_certificates.yaml#/components/schemas/DC400/properties/schema_version"
      - "digital_certificates.yaml#/components/schemas/DC403/properties/schema_version"
      - "digital_certificates.yaml#/components/schemas/DC404/properties/schema_version"
      - "digital_certificates.yaml#/components/schemas/DC406/properties/schema_version"
      - "digital_certificates.yaml#/components/schemas/DC409/properties/schema_version"
    rules:
      azion-number-minimum-limit-rule: "off"
  - files:
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/id"
      - "digital_certificates.yaml#/components/schemas/DC200/properties/schema_version"
      - "digital_certificates.yaml#/components/schemas/DC200List/properties/count"
      - "digital_certificates.yaml#/components/schemas/DC200List/properties/total_pages"
      - "digital_certificates.yaml#/components/schemas/DC200List/properties/schema_version"
      - "digital_certificates.yaml#/components/schemas/DC400/properties/schema_version"
      - "digital_certificates.yaml#/components/schemas/DC403/properties/schema_version"
      - "digital_certificates.yaml#/components/schemas/DC404/properties/schema_version"
      - "digital_certificates.yaml#/components/schemas/DC406/properties/schema_version"
      - "digital_certificates.yaml#/components/schemas/DC409/properties/schema_version"
    rules:
      azion-number-maximum-limit-rule: "off"
  - files:
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/name"
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/status"
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/azion_information"
      - "digital_certificates.yaml#/components/schemas/DC401/properties/detail"
    rules:
      azion-string-minlength-properties-rule: "off"
  - files:
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/name"
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/issuer"
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/validity"
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/status"
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/csr"
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/certificate_content"
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/azion_information"
      - "digital_certificates.yaml#/components/schemas/DC401/properties/detail"
    rules:
      azion-string-maxlength-properties-rule: "off"
  - files:
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/name"
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/issuer"
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/validity"
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/status"
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/csr"
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/certificate_content"
      - "digital_certificates.yaml#/components/schemas/singleResult/properties/azion_information"
      - "digital_certificates.yaml#/components/schemas/DC401/properties/detail"
    rules:
      azion-string-pattern-properties-rule: "off"