extends: .spectral.yaml
overrides:
  - files:
      - "waf.yaml#/paths/~1waf"
      - "waf.yaml#/paths/~1waf~1rulesets"
      - "waf.yaml#/paths/~1waf~1%7Bwaf_id%7D~1domains"
      - "waf.yaml#/paths/~1waf~1%7Bwaf_id%7D~1waf_events"
      - "waf.yaml#/paths/~1waf~1rulesets~1%7Bwaf_rule_set_id%7D"
    rules:
      azion-mandatory-status-codes: "off"
  - files:
      - "waf.yaml#/components/schemas/SingleWAF/properties/id"
      - "waf.yaml#/components/schemas/WAFList200/properties/count"
      - "waf.yaml#/components/schemas/WAFList200/properties/total_pages"
      - "waf.yaml#/components/schemas/WAFList200/properties/schema_version"
      - "waf.yaml#/components/schemas/WAFSingle200/properties/schema_version"
      - "waf.yaml#/components/schemas/WAFDomainList200/properties/id"
      - "waf.yaml#/components/schemas/WAFDomains200/properties/count"
      - "waf.yaml#/components/schemas/WAFDomains200/properties/total_pages"
      - "waf.yaml#/components/schemas/WAFDomains200/properties/schema_version"
      - "waf.yaml#/components/schemas/WAFEvents400/properties/schema_version"
      - "waf.yaml#/components/schemas/WAFEvents404/properties/schema_version"
      - "waf.yaml#/components/schemas/WAFEvents200/properties/schema_version"
    rules:
      azion-number-maximum-limit-rule: "off"
  - files:
      - "waf.yaml#/components/schemas/SingleWAF/properties/id"
      - "waf.yaml#/components/schemas/WAFList200/properties/count"
      - "waf.yaml#/components/schemas/WAFList200/properties/total_pages"
      - "waf.yaml#/components/schemas/WAFList200/properties/schema_version"
      - "waf.yaml#/components/schemas/WAFSingle200/properties/schema_version"
      - "waf.yaml#/components/schemas/WAFDomainList200/properties/id"
      - "waf.yaml#/components/schemas/WAFDomains200/properties/count"
      - "waf.yaml#/components/schemas/WAFDomains200/properties/total_pages"
      - "waf.yaml#/components/schemas/WAFDomains200/properties/schema_version"
      - "waf.yaml#/components/schemas/WAFEvents400/properties/schema_version"
      - "waf.yaml#/components/schemas/WAFEvents404/properties/schema_version"
      - "waf.yaml#/components/schemas/WAFEvents200/properties/schema_version"
    rules:
      azion-number-minimum-limit-rule: "off"
  - files:
      - "waf.yaml#/components/schemas/Links/properties/previous"
      - "waf.yaml#/components/schemas/Links/properties/next"
      - "waf.yaml#/components/schemas/SingleWAF/properties/name"
      - "waf.yaml#/components/schemas/WAFDomainList200/properties/name"
      - "waf.yaml#/components/schemas/WAFDomainList200/properties/domain"
      - "waf.yaml#/components/schemas/WAFEvents401/properties/detail"
    rules:
      azion-string-maxlength-properties-rule: "off"
  - files:
      - "waf.yaml#/components/schemas/SingleWAF/properties/name"
      - "waf.yaml#/components/schemas/WAFDomainList200/properties/name"
      - "waf.yaml#/components/schemas/WAFDomainList200/properties/domain"
      - "waf.yaml#/components/schemas/WAFEvents401/properties/detail"
    rules:
      azion-string-minlength-properties-rule: "off"
  - files:
      - "waf.yaml#/components/schemas/Links/properties/previous"
      - "waf.yaml#/components/schemas/Links/properties/next"
      - "waf.yaml#/components/schemas/SingleWAF/properties/name"
      - "waf.yaml#/components/schemas/WAFDomainList200/properties/name"
      - "waf.yaml#/components/schemas/WAFDomainList200/properties/domain"
      - "waf.yaml#/components/schemas/WAFEvents401/properties/detail"
    rules:
      azion-string-pattern-properties-rule: "off"  