functions: 
  - ./checkEndpointStatusCodes
  - ./checkNumberMinimumLimit
  - ./checkNumberMaximumLimit
  - ./checkStringMinLength
  - ./checkStringMaxLength
  - ./checkStringPattern
extends: spectral:oas
rules:
  azion-mandatory-status-codes:
    message: "{{error}}"
    severity: error
    given: "$.paths.*"
    then:
      function: checkEndpointStatusCodes
  azion-number-minimum-limit-rule:
    message: "{{error}}"
    severity: error
    given: "$.components.schemas.*.properties.*"
    then:
      function: checkNumberMinimumLimit
  azion-number-maximum-limit-rule:
    message: "{{error}}"
    severity: error
    given: "$.components.schemas.*.properties.*"
    then:
      function: checkNumberMaximumLimit
  azion-string-minlength-properties-rule:
    message: "{{error}}"
    severity: error
    given: "$.components.schemas.*.properties.*"
    then:
      function: checkStringMinLength
  azion-string-maxlength-properties-rule:
    message: "{{error}}"
    severity: error
    given: "$.components.schemas.*.properties.*"
    then:
      function: checkStringMaxLength
  azion-string-pattern-properties-rule:
    message: "{{error}}"
    severity: error
    given: "$.components.schemas.*.properties.*"
    then:
      function: checkStringPattern