extends: .spectral.yaml
overrides:
  - files:
      - "networklist.yaml#/paths/~1network_lists"
      - "networklist.yaml#/paths/~1network_lists~1%7Buuid%7D"
    rules:
      azion-mandatory-status-codes: "off"
  - files:
      - "networklist.yaml#/components/schemas/NetworkLists/properties/id"
      - "networklist.yaml#/components/schemas/ListNetworkListsResponse/properties/count"
      - "networklist.yaml#/components/schemas/ListNetworkListsResponse/properties/total_pages"
      - "networklist.yaml#/components/schemas/ListNetworkListsResponse/properties/schema_version"
      - "networklist.yaml#/components/schemas/NetworkListResponseEntry/properties/id"
      - "networklist.yaml#/components/schemas/NetworkListsResponse/properties/schema_version"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponse/properties/schema_version"
    rules:
      azion-number-minimum-limit-rule: "off"
  - files:
      - "networklist.yaml#/components/schemas/NetworkLists/properties/id"
      - "networklist.yaml#/components/schemas/ListNetworkListsResponse/properties/count"
      - "networklist.yaml#/components/schemas/ListNetworkListsResponse/properties/total_pages"
      - "networklist.yaml#/components/schemas/ListNetworkListsResponse/properties/schema_version"
      - "networklist.yaml#/components/schemas/NetworkListResponseEntry/properties/id"
      - "networklist.yaml#/components/schemas/NetworkListsResponse/properties/schema_version"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponse/properties/schema_version"
    rules:
      azion-number-maximum-limit-rule: "off"
  - files:
      - "networklist.yaml#/components/schemas/ErrorModel/properties/code"
      - "networklist.yaml#/components/schemas/NetworkLists/properties/last_editor"
      - "networklist.yaml#/components/schemas/NetworkLists/properties/last_modified"
      - "networklist.yaml#/components/schemas/NetworkLists/properties/list_type"
      - "networklist.yaml#/components/schemas/NetworkLists/properties/name"
      - "networklist.yaml#/components/schemas/NetworkListResponseEntry/properties/last_editor"
      - "networklist.yaml#/components/schemas/NetworkListResponseEntry/properties/last_modified"
      - "networklist.yaml#/components/schemas/NetworkListResponseEntry/properties/list_type"
      - "networklist.yaml#/components/schemas/NetworkListResponseEntry/properties/name"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryString/properties/name"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryString/properties/last_editor"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryString/properties/last_modified"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryString/properties/list_type"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryInt/properties/last_editor"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryInt/properties/last_modified"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryInt/properties/list_type"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryInt/properties/name"
      - "networklist.yaml#/components/schemas/CreateNetworkListsRequest/properties/name"
    rules:
      azion-string-minlength-properties-rule: "off"
  - files:
      - "networklist.yaml#/components/schemas/ErrorModel/properties/code"
      - "networklist.yaml#/components/schemas/Links/properties/previous"
      - "networklist.yaml#/components/schemas/Links/properties/next"
      - "networklist.yaml#/components/schemas/NetworkLists/properties/last_editor"
      - "networklist.yaml#/components/schemas/NetworkLists/properties/last_modified"
      - "networklist.yaml#/components/schemas/NetworkLists/properties/list_type"
      - "networklist.yaml#/components/schemas/NetworkLists/properties/name"
      - "networklist.yaml#/components/schemas/NetworkListResponseEntry/properties/last_editor"
      - "networklist.yaml#/components/schemas/NetworkListResponseEntry/properties/last_modified"
      - "networklist.yaml#/components/schemas/NetworkListResponseEntry/properties/list_type"
      - "networklist.yaml#/components/schemas/NetworkListResponseEntry/properties/name"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryString/properties/name"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryString/properties/last_editor"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryString/properties/last_modified"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryString/properties/list_type"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryInt/properties/last_editor"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryInt/properties/last_modified"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryInt/properties/list_type"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryInt/properties/name"
      - "networklist.yaml#/components/schemas/CreateNetworkListsRequest/properties/name"
    rules:
      azion-string-maxlength-properties-rule: "off"
  - files:
      - "networklist.yaml#/components/schemas/ErrorModel/properties/code"
      - "networklist.yaml#/components/schemas/Links/properties/previous"
      - "networklist.yaml#/components/schemas/Links/properties/next"
      - "networklist.yaml#/components/schemas/NetworkLists/properties/last_editor"
      - "networklist.yaml#/components/schemas/NetworkLists/properties/last_modified"
      - "networklist.yaml#/components/schemas/NetworkLists/properties/list_type"
      - "networklist.yaml#/components/schemas/NetworkLists/properties/name"
      - "networklist.yaml#/components/schemas/NetworkListResponseEntry/properties/last_editor"
      - "networklist.yaml#/components/schemas/NetworkListResponseEntry/properties/last_modified"
      - "networklist.yaml#/components/schemas/NetworkListResponseEntry/properties/list_type"
      - "networklist.yaml#/components/schemas/NetworkListResponseEntry/properties/name"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryString/properties/name"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryString/properties/last_editor"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryString/properties/last_modified"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryString/properties/list_type"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryInt/properties/last_editor"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryInt/properties/last_modified"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryInt/properties/list_type"
      - "networklist.yaml#/components/schemas/NetworkListUuidResponseEntryInt/properties/name"
      - "networklist.yaml#/components/schemas/CreateNetworkListsRequest/properties/name"
    rules:
      azion-string-pattern-properties-rule: "off"