extends: .spectral.yaml
overrides:
  - files:
      - "edgenode.yaml#"
    rules:
      azion-string-pattern-properties-rule: "off"
  - files:
      - "edgenode.yaml#/paths/~1edge_nodes"
      - "edgenode.yaml#/paths/~1edge_nodes~1authorize"
      - "edgenode.yaml#/paths/~1edge_nodes~1groups"
      - "edgenode.yaml#/paths/~1edge_nodes~1%7BedgenodeId%7D"
      - "edgenode.yaml#/paths/~1edge_nodes~1%7BedgenodeId%7D~1services"
      - "edgenode.yaml#/paths/~1edge_nodes~1%7BedgenodeId%7D~1services~1%7BbindId%7D"
    rules:
      azion-mandatory-status-codes: "off"
  - files:
      - "edgenode.yaml#/components/schemas/EdgeNodeDetailResponse/properties/id"
      - "edgenode.yaml#/components/schemas/EdgeNodeResponse/properties/id"
      - "edgenode.yaml#/components/schemas/EdgeNodeResponseWithTotal/properties/total"
      - "edgenode.yaml#/components/schemas/NodeGroup/properties/id"
      - "edgenode.yaml#/components/schemas/NodeGroupResponse/properties/id"
      - "edgenode.yaml#/components/schemas/ServiceBindDetailResponse/properties/id"
      - "edgenode.yaml#/components/schemas/ServiceBindDetailResponse/properties/service_id"
      - "edgenode.yaml#/components/schemas/ServiceBindRequest/properties/service_id"
      - "edgenode.yaml#/components/schemas/ServiceResponse/properties/bind_id"
      - "edgenode.yaml#/components/schemas/ServiceResponse/properties/is_bound"
      - "edgenode.yaml#/components/schemas/ServiceResponse/properties/service_id"
      - "edgenode.yaml#/components/schemas/ServiceResponseWithTotal/properties/total"
      - "edgenode.yaml#/components/schemas/UnauthorizedEdgeNodeInfo/properties/id"
      - "edgenode.yaml#/components/schemas/UpdateEdgeNodeResponse/properties/id"
    rules:
      azion-number-minimum-limit-rule: "off"
  - files:
      - "edgenode.yaml#/components/schemas/EdgeNodeDetailResponse/properties/id"
      - "edgenode.yaml#/components/schemas/EdgeNodeResponse/properties/id"
      - "edgenode.yaml#/components/schemas/EdgeNodeResponseWithTotal/properties/total"
      - "edgenode.yaml#/components/schemas/NodeGroup/properties/id"
      - "edgenode.yaml#/components/schemas/NodeGroupResponse/properties/id"
      - "edgenode.yaml#/components/schemas/ServiceBindDetailResponse/properties/id"
      - "edgenode.yaml#/components/schemas/ServiceBindDetailResponse/properties/service_id"
      - "edgenode.yaml#/components/schemas/ServiceBindRequest/properties/service_id"
      - "edgenode.yaml#/components/schemas/ServiceResponse/properties/bind_id"
      - "edgenode.yaml#/components/schemas/ServiceResponse/properties/is_bound"
      - "edgenode.yaml#/components/schemas/ServiceResponse/properties/service_id"
      - "edgenode.yaml#/components/schemas/ServiceResponseWithTotal/properties/total"
      - "edgenode.yaml#/components/schemas/UnauthorizedEdgeNodeInfo/properties/id"
      - "edgenode.yaml#/components/schemas/UpdateEdgeNodeResponse/properties/id"
    rules:
      azion-number-maximum-limit-rule: "off"
  - files:
      - "edgenode.yaml#/components/schemas/EdgeNodeDetailResponse/properties/hash_id"
      - "edgenode.yaml#/components/schemas/EdgeNodeDetailResponse/properties/name"
      - "edgenode.yaml#/components/schemas/EdgeNodeResponse/properties/hash_id"
      - "edgenode.yaml#/components/schemas/EdgeNodeResponse/properties/name"
      - "edgenode.yaml#/components/schemas/EdgeNodeResponse/properties/status"
      - "edgenode.yaml#/components/schemas/NodeGroup/properties/name"
      - "edgenode.yaml#/components/schemas/NodeGroupResponse/properties/name"
      - "edgenode.yaml#/components/schemas/ServiceBindDetailResponse/properties/service_name"
      - "edgenode.yaml#/components/schemas/ServiceResponse/properties/last_editor"
      - "edgenode.yaml#/components/schemas/ServiceResponse/properties/name"
      - "edgenode.yaml#/components/schemas/UnauthorizedEdgeNodeInfo/properties/reason"
      - "edgenode.yaml#/components/schemas/UpdateEdgeNodeResponse/properties/name"
      - "edgenode.yaml#/components/schemas/UpdateEdgeNodeResponse/properties/status"
      - "edgenode.yaml#/components/schemas/Variable/properties/name"
      - "edgenode.yaml#/components/schemas/Variable/properties/value"
    rules:
      azion-string-minlength-properties-rule: "off"
  - files:
      - "edgenode.yaml#/components/schemas/EdgeNodeDetailResponse/properties/hash_id"
      - "edgenode.yaml#/components/schemas/EdgeNodeDetailResponse/properties/name"
      - "edgenode.yaml#/components/schemas/EdgeNodeResponse/properties/hash_id"
      - "edgenode.yaml#/components/schemas/EdgeNodeResponse/properties/name"
      - "edgenode.yaml#/components/schemas/EdgeNodeResponse/properties/status"
      - "edgenode.yaml#/components/schemas/NodeGroup/properties/name"
      - "edgenode.yaml#/components/schemas/NodeGroupResponse/properties/name"
      - "edgenode.yaml#/components/schemas/ServiceBindDetailResponse/properties/service_name"
      - "edgenode.yaml#/components/schemas/ServiceResponse/properties/last_editor"
      - "edgenode.yaml#/components/schemas/ServiceResponse/properties/name"
      - "edgenode.yaml#/components/schemas/UnauthorizedEdgeNodeInfo/properties/reason"
      - "edgenode.yaml#/components/schemas/UpdateEdgeNodeResponse/properties/name"
      - "edgenode.yaml#/components/schemas/UpdateEdgeNodeResponse/properties/status"
      - "edgenode.yaml#/components/schemas/Variable/properties/name"
      - "edgenode.yaml#/components/schemas/Variable/properties/value"
    rules:
      azion-string-maxlength-properties-rule: "off"
  - files:
      - "edgenode.yaml#/components/schemas/EdgeNodeDetailResponse/properties/hash_id"
      - "edgenode.yaml#/components/schemas/EdgeNodeDetailResponse/properties/name"
      - "edgenode.yaml#/components/schemas/EdgeNodeResponse/properties/hash_id"
      - "edgenode.yaml#/components/schemas/EdgeNodeResponse/properties/name"
      - "edgenode.yaml#/components/schemas/EdgeNodeResponse/properties/status"
      - "edgenode.yaml#/components/schemas/NodeGroup/properties/name"
      - "edgenode.yaml#/components/schemas/NodeGroupResponse/properties/name"
      - "edgenode.yaml#/components/schemas/ServiceBindDetailResponse/properties/service_name"
      - "edgenode.yaml#/components/schemas/ServiceResponse/properties/last_editor"
      - "edgenode.yaml#/components/schemas/ServiceResponse/properties/name"
      - "edgenode.yaml#/components/schemas/UnauthorizedEdgeNodeInfo/properties/reason"
      - "edgenode.yaml#/components/schemas/UpdateEdgeNodeResponse/properties/name"
      - "edgenode.yaml#/components/schemas/UpdateEdgeNodeResponse/properties/status"
      - "edgenode.yaml#/components/schemas/Variable/properties/name"
      - "edgenode.yaml#/components/schemas/Variable/properties/value"
    rules:
      azion-string-pattern-properties-rule: "off"