extends: .spectral.yaml
overrides:
  - files:
      - "credentials.yaml#/paths/~1credentials"
      - "credentials.yaml#/paths/~1credentials~1%7BcredentialId%7D"
    rules:
      azion-mandatory-status-codes: "off"
  - files:
      - "credentials.yaml#/components/schemas/AuthToken/properties/id"
      - "credentials.yaml#/components/schemas/Response/properties/id"
      - "credentials.yaml#/components/schemas/ResponseWithTotal/properties/total"
    rules:
      azion-number-minimum-limit-rule: "off"
  - files:
      - "credentials.yaml#/components/schemas/AuthToken/properties/id"
      - "credentials.yaml#/components/schemas/Response/properties/id"
      - "credentials.yaml#/components/schemas/ResponseWithTotal/properties/total"
    rules:
      azion-number-maximum-limit-rule: "off"
  - files:
      - "credentials.yaml#/components/schemas/AuthToken/properties/client_id"
      - "credentials.yaml#/components/schemas/AuthToken/properties/description"
      - "credentials.yaml#/components/schemas/AuthToken/properties/last_editor"
      - "credentials.yaml#/components/schemas/AuthToken/properties/name"
      - "credentials.yaml#/components/schemas/AuthToken/properties/token"
      - "credentials.yaml#/components/schemas/CreateCredentialRequest/properties/description"
      - "credentials.yaml#/components/schemas/CreateCredentialRequest/properties/name"
      - "credentials.yaml#/components/schemas/Response/properties/description"
      - "credentials.yaml#/components/schemas/Response/properties/last_editor"
      - "credentials.yaml#/components/schemas/Response/properties/name"
      - "credentials.yaml#/components/schemas/Response/properties/token"
      - "credentials.yaml#/components/schemas/UpdateCredentialRequest/properties/description"
      - "credentials.yaml#/components/schemas/UpdateCredentialRequest/properties/name"
    rules:
      azion-string-minlength-properties-rule: "off"
  - files:
      - "credentials.yaml#/components/schemas/AuthToken/properties/client_id"
      - "credentials.yaml#/components/schemas/AuthToken/properties/description"
      - "credentials.yaml#/components/schemas/AuthToken/properties/last_editor"
      - "credentials.yaml#/components/schemas/AuthToken/properties/name"
      - "credentials.yaml#/components/schemas/AuthToken/properties/token"
      - "credentials.yaml#/components/schemas/CreateCredentialRequest/properties/description"
      - "credentials.yaml#/components/schemas/CreateCredentialRequest/properties/name"
      - "credentials.yaml#/components/schemas/Response/properties/description"
      - "credentials.yaml#/components/schemas/Response/properties/last_editor"
      - "credentials.yaml#/components/schemas/Response/properties/name"
      - "credentials.yaml#/components/schemas/Response/properties/token"
      - "credentials.yaml#/components/schemas/UpdateCredentialRequest/properties/description"
      - "credentials.yaml#/components/schemas/UpdateCredentialRequest/properties/name"
    rules:
      azion-string-maxlength-properties-rule: "off"
  - files:
      - "credentials.yaml#/components/schemas/AuthToken/properties/client_id"
      - "credentials.yaml#/components/schemas/AuthToken/properties/description"
      - "credentials.yaml#/components/schemas/AuthToken/properties/last_editor"
      - "credentials.yaml#/components/schemas/AuthToken/properties/name"
      - "credentials.yaml#/components/schemas/AuthToken/properties/token"
      - "credentials.yaml#/components/schemas/CreateCredentialRequest/properties/description"
      - "credentials.yaml#/components/schemas/CreateCredentialRequest/properties/name"
      - "credentials.yaml#/components/schemas/Response/properties/description"
      - "credentials.yaml#/components/schemas/Response/properties/last_editor"
      - "credentials.yaml#/components/schemas/Response/properties/name"
      - "credentials.yaml#/components/schemas/Response/properties/token"
      - "credentials.yaml#/components/schemas/UpdateCredentialRequest/properties/description"
      - "credentials.yaml#/components/schemas/UpdateCredentialRequest/properties/name"
    rules:
      azion-string-pattern-properties-rule: "off"