extends: .spectral.yaml
overrides:
  - files:
      - "edgefunctions.yaml#/paths/~1edge_functions"
      - "edgefunctions.yaml#/paths/~1edge_functions~1%7Bid%7D"
    rules:
      azion-mandatory-status-codes: "off"
  - files:
      - "edgefunctions.yaml#/components/schemas/Results/properties/id"
      - "edgefunctions.yaml#/components/schemas/Results/properties/reference_count"
      - "edgefunctions.yaml#/components/schemas/ListEdgeFunctionResponse/properties/count"
      - "edgefunctions.yaml#/components/schemas/ListEdgeFunctionResponse/properties/total_pages"
      - "edgefunctions.yaml#/components/schemas/ListEdgeFunctionResponse/properties/schema_version"
      - "edgefunctions.yaml#/components/schemas/EdgeFunctionResponse/properties/schema_version"
    rules:
      azion-number-minimum-limit-rule: "off"
  - files:
      - "edgefunctions.yaml#/components/schemas/Results/properties/id"
      - "edgefunctions.yaml#/components/schemas/Results/properties/reference_count"
      - "edgefunctions.yaml#/components/schemas/ListEdgeFunctionResponse/properties/count"
      - "edgefunctions.yaml#/components/schemas/ListEdgeFunctionResponse/properties/total_pages"
      - "edgefunctions.yaml#/components/schemas/ListEdgeFunctionResponse/properties/schema_version"
      - "edgefunctions.yaml#/components/schemas/EdgeFunctionResponse/properties/schema_version"
    rules:
      azion-number-maximum-limit-rule: "off"
  - files:
      - "edgefunctions.yaml#/components/schemas/ErrorResponse/properties/detail"
      - "edgefunctions.yaml#/components/schemas/Results/properties/name"
      - "edgefunctions.yaml#/components/schemas/Results/properties/language"
      - "edgefunctions.yaml#/components/schemas/Results/properties/code"
      - "edgefunctions.yaml#/components/schemas/Results/properties/function_to_run"
      - "edgefunctions.yaml#/components/schemas/Results/properties/initiator_type"
      - "edgefunctions.yaml#/components/schemas/Results/properties/last_editor"
      - "edgefunctions.yaml#/components/schemas/Results/properties/modified"
      - "edgefunctions.yaml#/components/schemas/CreateEdgeFunctionRequest/properties/name"
      - "edgefunctions.yaml#/components/schemas/CreateEdgeFunctionRequest/properties/language"
      - "edgefunctions.yaml#/components/schemas/CreateEdgeFunctionRequest/properties/code"
      - "edgefunctions.yaml#/components/schemas/PutEdgeFunctionRequest/properties/name"
      - "edgefunctions.yaml#/components/schemas/PutEdgeFunctionRequest/properties/code"
      - "edgefunctions.yaml#/components/schemas/PutEdgeFunctionRequest/properties/language"
      - "edgefunctions.yaml#/components/schemas/PatchEdgeFunctionRequest/properties/name"
      - "edgefunctions.yaml#/components/schemas/PatchEdgeFunctionRequest/properties/code"
    rules:
      azion-string-minlength-properties-rule: "off"
  - files:
      - "edgefunctions.yaml#/components/schemas/ErrorResponse/properties/detail"
      - "edgefunctions.yaml#/components/schemas/Links/properties/previous"
      - "edgefunctions.yaml#/components/schemas/Links/properties/next"
      - "edgefunctions.yaml#/components/schemas/Results/properties/name"
      - "edgefunctions.yaml#/components/schemas/Results/properties/language"
      - "edgefunctions.yaml#/components/schemas/Results/properties/code"
      - "edgefunctions.yaml#/components/schemas/Results/properties/function_to_run"
      - "edgefunctions.yaml#/components/schemas/Results/properties/initiator_type"
      - "edgefunctions.yaml#/components/schemas/Results/properties/last_editor"
      - "edgefunctions.yaml#/components/schemas/Results/properties/modified"
      - "edgefunctions.yaml#/components/schemas/CreateEdgeFunctionRequest/properties/name"
      - "edgefunctions.yaml#/components/schemas/CreateEdgeFunctionRequest/properties/language"
      - "edgefunctions.yaml#/components/schemas/CreateEdgeFunctionRequest/properties/code"
      - "edgefunctions.yaml#/components/schemas/PutEdgeFunctionRequest/properties/name"
      - "edgefunctions.yaml#/components/schemas/PutEdgeFunctionRequest/properties/code"
      - "edgefunctions.yaml#/components/schemas/PutEdgeFunctionRequest/properties/language"
      - "edgefunctions.yaml#/components/schemas/PatchEdgeFunctionRequest/properties/name"
      - "edgefunctions.yaml#/components/schemas/PatchEdgeFunctionRequest/properties/code"
    rules:
      azion-string-maxlength-properties-rule: "off"
  - files:
      - "edgefunctions.yaml#/components/schemas/ErrorResponse/properties/detail"
      - "edgefunctions.yaml#/components/schemas/Links/properties/previous"
      - "edgefunctions.yaml#/components/schemas/Links/properties/next"
      - "edgefunctions.yaml#/components/schemas/Results/properties/name"
      - "edgefunctions.yaml#/components/schemas/Results/properties/language"
      - "edgefunctions.yaml#/components/schemas/Results/properties/code"
      - "edgefunctions.yaml#/components/schemas/Results/properties/function_to_run"
      - "edgefunctions.yaml#/components/schemas/Results/properties/initiator_type"
      - "edgefunctions.yaml#/components/schemas/Results/properties/last_editor"
      - "edgefunctions.yaml#/components/schemas/Results/properties/modified"
      - "edgefunctions.yaml#/components/schemas/CreateEdgeFunctionRequest/properties/name"
      - "edgefunctions.yaml#/components/schemas/CreateEdgeFunctionRequest/properties/language"
      - "edgefunctions.yaml#/components/schemas/CreateEdgeFunctionRequest/properties/code"
      - "edgefunctions.yaml#/components/schemas/PutEdgeFunctionRequest/properties/name"
      - "edgefunctions.yaml#/components/schemas/PutEdgeFunctionRequest/properties/code"
      - "edgefunctions.yaml#/components/schemas/PutEdgeFunctionRequest/properties/language"
      - "edgefunctions.yaml#/components/schemas/PatchEdgeFunctionRequest/properties/name"
      - "edgefunctions.yaml#/components/schemas/PatchEdgeFunctionRequest/properties/code"
    rules:
      azion-string-pattern-properties-rule: "off"