extends: .spectral.yaml
overrides:
  - files:
      - "services.yaml#/paths/~1edge_services"
      - "services.yaml#/paths/~1edge_services~1%7Bid%7D"
      - "services.yaml#/paths/~1edge_services~1%7BserviceId%7D~1resources"
      - "services.yaml#/paths/~1edge_services~1%7BserviceId%7D~1resources~1%7BresourceId%7D"
    rules:
      azion-mandatory-status-codes: "off"
  - files:
      - "services.yaml#/components/schemas/ResourceDetail/properties/id"
      - "services.yaml#/components/schemas/ResourceResponse/properties/id"
      - "services.yaml#/components/schemas/ServiceResponse/properties/bound_nodes"
      - "services.yaml#/components/schemas/ServiceResponse/properties/id"
      - "services.yaml#/components/schemas/ServiceResponseWithTotals/properties/total"
    rules:
      azion-number-minimum-limit-rule: "off"
  - files:
      - "services.yaml#/components/schemas/ResourceDetail/properties/id"
      - "services.yaml#/components/schemas/ResourceResponse/properties/id"
      - "services.yaml#/components/schemas/ServiceResponse/properties/bound_nodes"
      - "services.yaml#/components/schemas/ServiceResponse/properties/id"
      - "services.yaml#/components/schemas/ServiceResponseWithTotals/properties/total"
    rules:
      azion-number-maximum-limit-rule: "off"
  - files:
      - "services.yaml#/components/schemas/CreateResourceRequest/properties/name"
      - "services.yaml#/components/schemas/CreateResourceRequest/properties/trigger"
      - "services.yaml#/components/schemas/CreateResourceRequest/properties/content"
      - "services.yaml#/components/schemas/CreateResourceRequest/properties/content_type"
      - "services.yaml#/components/schemas/CreateServiceRequest/properties/name"
      - "services.yaml#/components/schemas/ResourceDetail/properties/content"
      - "services.yaml#/components/schemas/ResourceDetail/properties/content_type"
      - "services.yaml#/components/schemas/ResourceDetail/properties/name"
      - "services.yaml#/components/schemas/ResourceDetail/properties/trigger"
      - "services.yaml#/components/schemas/ResourceResponse/properties/content_type"
      - "services.yaml#/components/schemas/ResourceResponse/properties/last_editor"
      - "services.yaml#/components/schemas/ResourceResponse/properties/name"
      - "services.yaml#/components/schemas/ResourceResponse/properties/trigger"
      - "services.yaml#/components/schemas/ResourceResponse/properties/updated_at"
      - "services.yaml#/components/schemas/ServiceResponse/properties/last_editor"
      - "services.yaml#/components/schemas/ServiceResponse/properties/name"
      - "services.yaml#/components/schemas/ServiceResponse/properties/updated_at"
      - "services.yaml#/components/schemas/UpdateResourceRequest/properties/content"
      - "services.yaml#/components/schemas/UpdateResourceRequest/properties/content_type"
      - "services.yaml#/components/schemas/UpdateResourceRequest/properties/name"
      - "services.yaml#/components/schemas/UpdateResourceRequest/properties/trigger"
      - "services.yaml#/components/schemas/UpdateServiceRequest/properties/name"
      - "services.yaml#/components/schemas/Variable/properties/name"
      - "services.yaml#/components/schemas/Variable/properties/value"
    rules:
      azion-string-minlength-properties-rule: "off"
  - files:
      - "services.yaml#/components/schemas/CreateResourceRequest/properties/name"
      - "services.yaml#/components/schemas/CreateResourceRequest/properties/trigger"
      - "services.yaml#/components/schemas/CreateResourceRequest/properties/content"
      - "services.yaml#/components/schemas/CreateResourceRequest/properties/content_type"
      - "services.yaml#/components/schemas/CreateServiceRequest/properties/name"
      - "services.yaml#/components/schemas/ResourceDetail/properties/content"
      - "services.yaml#/components/schemas/ResourceDetail/properties/content_type"
      - "services.yaml#/components/schemas/ResourceDetail/properties/name"
      - "services.yaml#/components/schemas/ResourceDetail/properties/trigger"
      - "services.yaml#/components/schemas/ResourceResponse/properties/content_type"
      - "services.yaml#/components/schemas/ResourceResponse/properties/last_editor"
      - "services.yaml#/components/schemas/ResourceResponse/properties/name"
      - "services.yaml#/components/schemas/ResourceResponse/properties/trigger"
      - "services.yaml#/components/schemas/ResourceResponse/properties/updated_at"
      - "services.yaml#/components/schemas/ServiceResponse/properties/last_editor"
      - "services.yaml#/components/schemas/ServiceResponse/properties/name"
      - "services.yaml#/components/schemas/ServiceResponse/properties/updated_at"
      - "services.yaml#/components/schemas/UpdateResourceRequest/properties/content"
      - "services.yaml#/components/schemas/UpdateResourceRequest/properties/content_type"
      - "services.yaml#/components/schemas/UpdateResourceRequest/properties/name"
      - "services.yaml#/components/schemas/UpdateResourceRequest/properties/trigger"
      - "services.yaml#/components/schemas/UpdateServiceRequest/properties/name"
      - "services.yaml#/components/schemas/Variable/properties/name"
      - "services.yaml#/components/schemas/Variable/properties/value"
    rules:
      azion-string-maxlength-properties-rule: "off"
  - files:
      - "services.yaml#/components/schemas/CreateResourceRequest/properties/name"
      - "services.yaml#/components/schemas/CreateResourceRequest/properties/trigger"
      - "services.yaml#/components/schemas/CreateResourceRequest/properties/content"
      - "services.yaml#/components/schemas/CreateResourceRequest/properties/content_type"
      - "services.yaml#/components/schemas/CreateServiceRequest/properties/name"
      - "services.yaml#/components/schemas/ResourceDetail/properties/content"
      - "services.yaml#/components/schemas/ResourceDetail/properties/content_type"
      - "services.yaml#/components/schemas/ResourceDetail/properties/name"
      - "services.yaml#/components/schemas/ResourceDetail/properties/trigger"
      - "services.yaml#/components/schemas/ResourceResponse/properties/content_type"
      - "services.yaml#/components/schemas/ResourceResponse/properties/last_editor"
      - "services.yaml#/components/schemas/ResourceResponse/properties/name"
      - "services.yaml#/components/schemas/ResourceResponse/properties/trigger"
      - "services.yaml#/components/schemas/ResourceResponse/properties/updated_at"
      - "services.yaml#/components/schemas/ServiceResponse/properties/last_editor"
      - "services.yaml#/components/schemas/ServiceResponse/properties/name"
      - "services.yaml#/components/schemas/ServiceResponse/properties/updated_at"
      - "services.yaml#/components/schemas/UpdateResourceRequest/properties/content"
      - "services.yaml#/components/schemas/UpdateResourceRequest/properties/content_type"
      - "services.yaml#/components/schemas/UpdateResourceRequest/properties/name"
      - "services.yaml#/components/schemas/UpdateResourceRequest/properties/trigger"
      - "services.yaml#/components/schemas/UpdateServiceRequest/properties/name"
      - "services.yaml#/components/schemas/Variable/properties/name"
      - "services.yaml#/components/schemas/Variable/properties/value"
    rules:
      azion-string-pattern-properties-rule: "off"