extends: .spectral.yaml
overrides:
  - files:
      - "storage.yaml#/components/schemas/PaginatedBucketList/properties/count"
      - "storage.yaml#/components/schemas/PaginatedBucketObjectList/properties/count"
    rules:
      azion-number-minimum-limit-rule: "off"
  - files:
      - "storage.yaml#/components/schemas/PaginatedBucketList/properties/count"
      - "storage.yaml#/components/schemas/PaginatedBucketObjectList/properties/count"
    rules:
      azion-number-maximum-limit-rule: "off"
  - files:
      - "storage.yaml#/components/schemas/BucketCreate/properties/name"
      - "storage.yaml#/components/schemas/ObjectResponseData/properties/object_key"
    rules:
      azion-string-pattern-properties-rule: "off"
  - files:
      - "storage.yaml#/components/schemas/ObjectResponseData/properties/object_key"
    rules:
      azion-string-maxlength-properties-rule: "off"
  - files:
      - "storage.yaml#/components/schemas/ObjectResponseData/properties/object_key"
    rules:
      azion-string-minlength-properties-rule: "off"
    