name: OpenAPI Spectral Linter

on:
  pull_request:
    branches:
        - main

jobs:
  spectral:
    runs-on: [ self-hosted, stage ]
    container:
      image: node:14-alpine3.12

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Checkout azion-api-template
        uses: actions/checkout@v3
        with:
          repository: aziontech/azion-api-template
          token: ${{ secrets.GLOBAL_TOKEN }}
          path: azion-api-template
          ref: QA-1322

      - name: Install Spectral
        run: npm install @stoplight/spectral-cli

      - name: Run Spectral Lint
        run: npx spectral lint --verbose --ruleset .spectral.yaml *.yaml --display-only-failures || exit 1
